### ISSUE TITLE
Sitewhere fetching data and integrations

### ISSUE THREAD

**Issue by amrdruid** [sitewhere/sitewhere#100]
Hello there, first I want to thank you for the awesome support on the open/closed issues here on Github.

We have a use-case where we have our own analytical end project and we want to fetch data from SiteWhere and push it to our Dashboard.

I guess for this simple scenario we have two approaches

1) Use SiteWhere REST APIs 

2) Use another software integration (mulsoft for example)

for this use-case what do you prefer ? I current saw that Mule AnyPoint Platform doesn't send data to a third party unless it's deployed locally. Which approach would you suggest ?

**Comment by derekadams** [comment]
Probably the easiest approach is to forward events via MQTT. You can add an outbound MQTT event processor to send events to a pre-determined topic and have your analytics system listen on that topic.

![image](https://cloud.githubusercontent.com/assets/338921/24985059/c4d7bffe-1fbf-11e7-967c-8f874cfa9103.png)

We also support forwarding via Hazelcast, sending events to Amazon SQS, Azure EventHubs, and many other approaches. One new option we will be adding in the 1.11 release is support for invoking a remote REST service for matching events.

Hope that helps!

Regards,
Derek

**Comment by amrdruid** [comment]
Thanks alot !
