### ISSUE TITLE
update one specification failed, all the specifications cannot show. error: Device specification has reference to non-existent asset.

### ISSUE THREAD

**Issue by murzhugit** [sitewhere/sitewhere#101]
I am using v1.8, after updating one specifcation, when apply changes, failed, then I refresh the specification page, unfortunately all the specifications were deleted, cannot show, but I query MongoDB, specification collection got datas. I encountered same issue when I update the tenant last time. Is this a bug fixed in v1.9??

**Comment by derekadams** [comment]
Is there an exception in the log file? Usually, if the specification list no longer displays, it means that some invalid data has been saved for a specification. There was a bug that prevented the specifications list from rendering in a previous version, but I was not able to find it in Jira. I would recommend upgrading to v1.9 to see if that fixes the problem.
