### ISSUE TITLE
Response to Locations

### ISSUE THREAD

**Issue by hoseinit** [sitewhere/sitewhere#14]
Hi, 
How is it possible to send response data to Devices after Receiving Locations on the server ?
I mean I want to send some information based on Devices Locations

**Comment by derekadams** [comment]
What type of response are you looking to send back to the device? If you want to send a command, you can use the embedded Siddhi instance to dynamically create commands for the locations. Take a look at the [end](http://documentation.sitewhere.org/integration/openhab.html#using-cep-with-openhab) of our openHAB tutorial for an example of using a Groovy script to dynamically generate commands. You can do simple things like a command per location or more complex things like send a command if no location events have been received for 5 minutes. We are also adding the ability to forward events to arbitrary MQTT topics in the 1.4.0 release that will be out at the end of the month.

**Comment by hoseinit** [comment]
Thanks alot for the rapid answer.
