### ISSUE TITLE
Tenant Engine: Default Tenant Error

### ISSUE THREAD

**Issue by hoseinit** [sitewhere/sitewhere#15]
Hi
I am new to Sitewhere,
After a fresh install of 1.3 version I get this error on Log file (sitewhere.log) and I can't login in the admin panel (http://localhost:8080/sitewhere/admin/server.html) because after login page with the default user/pass nothing apears on the mentioned url.
Thanks

**Comment by derekadams** [comment]
Please attach the complete log file and we will take a look. Thanks!

**Comment by hoseinit** [comment]
I don't know what caused the problem, but after reinstalling many times and switching among versions (1.1 , 1.2 and 1.3 ) eventually I succeeded to install an stable version newer than previously installed 1.0.5.

**Comment by hoseinit** [comment]
I know it's Completely irrelevant to this subject, but could you please solve my problem?
I want to execute a command upon a location update is received. but no command is executed.
I have defined siddhi-query in conf/sitewhere/default-tenant.xml as follows
```
<sw:siddhi-event-processor>
      <sw:siddhi-query
        selector="from e2 = LocationStream select e2.assignment, e2.latitude, e2.longitude insert into LocationChanged">
        <sw:groovy-stream-processor scriptPath="siddhiExecuteCommand.groovy" stream="LocationChanged"  />
      </sw:siddhi-query>
```
and my siddhiExecuteCommand.groovy is as follow:

```
// Get assignment token from event.
def assignment = event.getData(0)
logger.info("About to execute command to send traffic data for: " + assignment)

Map<String, Double> parameters = new HashMap<String, Double>();
parameters.put("lat", "35.69");
parameters.put("lng", "51.42");
parameters.put("color", "red");
actions.sendCommand(assignment, "myCommand", parameters);
```

but the "myCommand" is never invoked.
In the debug Also I never see the `"About to execute command to send traffic data for: " + assignedDevice`

All I see in the sitewhere.log is :

DEBUG [InboundEventSource] Device event receiver thread picked up event.
DEBUG [ProtobufDeviceEventDecoder]  Decoded location for: da8a0ac69ad9c44c
DEBUG [InboundEventSource]  Device event receiver thread picked up event.
DEBUG [ProtobufDeviceEventDecoder]  Decoded measurement for: da8a0ac69ad9c44c
DEBUG [DeviceEventBuffer]  Executing bulk insert of 1 event records.
DEBUG [GroovyStreamProcessor]  About to process 'siddhiExecuteCommand.groovy' with 1 events.
DEBUG [InboundEventSource]  Device event receiver thread picked up event.
DEBUG [ProtobufDeviceEventDecoder]  Decoded measurement for: da8a0ac69ad9c44c
DEBUG [InboundEventSource]  Device event receiver thread picked up event.
DEBUG [ProtobufDeviceEventDecoder]  Decoded measurement for: da8a0ac69ad9c44c
DEBUG [InboundEventSource]  Device event receiver thread picked up event.
DEBUG [ProtobufDeviceEventDecoder]  Decoded measurement for: da8a0ac69ad9c44c
DEBUG [DeviceEventBuffer]  Executing bulk insert of 4 event records.

**Comment by derekadams** [comment]
Which version of SiteWhere are you using? I copied the XML configuration and the content of the Groovy script to a SiteWhere 1.3.0 instance and it worked (it tried to execute the command when a new location was added). Double-check to make sure that the content of the script on disk (in conf/sitewhere/groovy/siddhiExecuteCommand.groovy) is what you pasted above. It looks like the script is being executed, but the lack of a logger message indicates it's not running the right script content.

**Comment by hoseinit** [comment]
Thank you for your time and generosity for answering my question.
I am using version 1.3 and the script and the config is as you see above. It seems the command is not invoked because:
1. The "logger.info" doesn't apear on the log file
2. The locations are not sent to my device (when I manually invoke myCommand the device gets the data)

**Comment by derekadams** [comment]
Were you able to fix the problem or is it still occurring? If it is not fixed, try deleting everything except the logger statement and see if it is executed. That way we can be sure that the script you are editing is indeed the one that SiteWhere is executing.

**Comment by hoseinit** [comment]
Actually no, there was no success in running the script. putting the logger aside, no command gets executed. but by manually Invoking the Command from Devices menu everything works fine.
Why it shows:
DEBUG [GroovyStreamProcessor] About to process 'siddhiExecuteCommand.groovy' with 1 events.
but afterward nothing happens? the file is there, the context you verified. So where is the problem initiated from ?

**Comment by derekadams** [comment]
I think what you are seeing may be related to a known [bug](https://sitewhere.atlassian.net/browse/SITEWHERE-234) in SiteWhere 1.3.0 that causes an exception when running Siddhi Groovy scripts. We will be releasing SiteWhere 1.4.0 in the next couple of days which should fix the issue. Sorry for the inconvenience.

**Comment by hoseinit** [comment]
Thank you a thousand time for answering questions and receiving feedback.

**Comment by derekadams** [comment]
We are glad to help. The SiteWhere 1.4.0 release is now available on the sitewhere.org website if you want to try it out. Hopefully, it fixes the problem you are running in to with scripting. If not, open this issue again and we will track down the problem.

**Comment by hoseinit** [comment]
Thank you very much. my problem solved. I did a fresh installation (mongodb erase dbs) of the latest version (1.4.0) and added my siddhiQuery to tenant configuration file and Groovy Script to it's location. It successfully invoked the desired command.
Again I'm grateful for your help.
