### ISSUE TITLE
send data from database to device

### ISSUE THREAD

**Issue by sadeqans** [sitewhere/sitewhere#17]
Hi
How is it possible to send  location all Devices  to Devices after Receiving Locations on the server ?

**Comment by sadeqans** [comment]
i mean i want read data from database and send that's to Devices in groovy
 please help me

**Comment by derekadams** [comment]
There are a few ways you can relay events from SiteWhere to devices depending on your requirements. If your device is capable of making an HTTP request, you can use the SiteWhere REST services to poll SiteWhere for a list of recent events. You can also use the outbound MQTT  processor to forward the events to devices is real time and use a Groovy script to decide routing. If you want to forward select events to a subset of devices you could also use SiteWhere commands to deliver the payloads (though there is more overhead). Finally, you can use Hazelcast or one of the other integration technologies to forward the events. It really depends on your use case. The most important considerations he capabilities of the devices you are using and the protocol you are using to connect.

**Comment by sadeqans** [comment]
i used MQTT protocol for connection between devices and sitewhere , and i used siddhi for execute trigger like this example(  Using CEP with openHAB      http://documentation.sitewhere.org/integration/openhab.html), but i will All data in the database forward to devices.

**Comment by sadeqans** [comment]
i mean every devices send some data to server(sitewhere) and they save in database, now i will send all of them to devices.

**Comment by derekadams** [comment]
If you want all device data to be forwarded over MQTT to the devices, you can use the new MQTT outbound event processor (http://documentation.sitewhere.org/userguide/tenant/event-processing.html#mqtt-event-processor). It will send all events to the specified topic. If your devices listen to the MQTT topic they will get all events. You can also use filters on the processor if you want to limit the events that are forwarded.

**Comment by sadeqans** [comment]
thanks for your answer
i used this siddhi
[New Text Document (4).txt](https://github.com/sitewhere/sitewhere/files/87253/New.Text.Document.4.txt)

**Comment by sadeqans** [comment]
in siddhiExecuteCammand ,i recieved just one event, but i will recieve more one event in this file
how i can fix that???

**Comment by sadeqans** [comment]
i used this mqtt inbound

 <sw:mqtt-event-processor hostname="localhost" port="1883">
                                <sw:filters>
                                        <sw:site-filter operation="include" site="bb105f8d-3150-41f5-b9d1-db04965668d3"/>
                                        <sw:specification-filter operation="exclude"
                                                specification="417b36a8-21ef-4196-a8fe-cc756f994d0b"/>
                                        <sw:groovy-filter scriptPath="filter.groovy"/>
                                </sw:filters>
                                <sw:groovy-route-builder scriptPath="route.groovy"/>
                        </sw:mqtt-event-processor>

 but This event is only received by the device that sent the event , how change that for all deceives received this event???

**Comment by derekadams** [comment]
What are you trying to accomplish with the Siddhi query? Normally, a time window is used for aggregation, but there is no 'group by' clause in the query. It's not apparent what the query is intended to do. One thing to take note of is that large time windows tend to be a bad idea since Siddhi has to keep all of the events in memory for that amount of time to process the window. If you have a system that generates 1 million location events per hour and a time window of 1 hour, there will be 1 million events in memory to allow for the function to work.

**Comment by sadeqans** [comment]
what are you'r offer for me??

**Comment by sadeqans** [comment]
how i can send event to all devices(broadcast) ??

**Comment by derekadams** [comment]
Add an MQTT outbound event processor as shown [here](http://documentation.sitewhere.org/userguide/tenant/event-processing.html#mqtt-event-processor) to send all events to any devices listening on the given topic. So, for instance, if you add:

```xml
<sw:outbound-processing-chain>
      
    <sw:mqtt-event-processor hostname="localhost" port="1883"
        protocol="tcp" topic="interested.devices"></sw:mqtt-event-processor>

</sw:outbound-processing-chain>
```

All interested devices should listen on the queue **interested.devices**.

**Comment by sadeqans** [comment]
thanks for your answer..
