### ISSUE TITLE
Including Wrong Javascript File

### ISSUE THREAD

**Issue by garysmi2** [sitewhere/sitewhere#19]
In sitewhere.web:

sitewhere-web/src/main/webapp/WEB-INF/jsp/login.jsp

Including kendo.web.js is resulting in a 404 error as it is the minified version that is in the scripts folder.

&lt;script src="${pageContext.request.contextPath}/scripts/kendo.web.js"&gt;&lt;/script&gt;

Should probably be 

&lt;script src="${pageContext.request.contextPath}/scripts/kendo.web.min.js"&gt;&lt;script&gt;

**Comment by derekadams** [comment]
Good catch. We swapped to the minified versions and forgot to update the login page. We added a [Jira issue](https://sitewhere.atlassian.net/browse/SITEWHERE-261?filter=11000) and committed a fix for the 1.6.0 branch.
