### ISSUE TITLE
Error Loading Page

### ISSUE THREAD

**Issue by sadeqans** [sitewhere/sitewhere#21]
hi
I was faced with a problem, i deleted default tenant in sitewhere 1.5 for test, but now sitewhere was error

below error in administrator page

Error Loading Page
User is not authorized to access any of the available tenants.

**Comment by derekadams** [comment]
This is a bug. If your user it a tenant administrator, they should be allowed to log in and add a tenant to make the system usable again. We added a Jira issue to fix the bug:

https://sitewhere.atlassian.net/browse/SITEWHERE-264

**Comment by sadeqans** [comment]
ok, thanks for your answer
