### ISSUE TITLE
Problem with deploying sitewhere mongodb

### ISSUE THREAD

**Issue by duybh** [sitewhere/sitewhere#26]
Hi Sitewhere team,

I'm pretty new to Sitewhere, and I tried to install the sitewhere mongodb on my Ubuntu 14.04 machine through Juju. However, I get an error: 'hook failed: "config-changed"'

What is the problem?

I just use the juju tutorial offered on Sitewhere. Here is my log:

2016-02-03 05:25:17 INFO config-changed   File "/var/lib/juju/agents/unit-mongodb-0/charm/hooks/hooks.py", line 1668, in <module>
2016-02-03 05:25:17 INFO config-changed     hooks.execute(sys.argv)
2016-02-03 05:25:17 INFO config-changed   File "/var/lib/juju/agents/unit-mongodb-0/charm/hooks/charmhelpers/core/hookenv.py", line 546, in execute
2016-02-03 05:25:17 INFO config-changed     self._hooks[hook_name]()
2016-02-03 05:25:17 INFO config-changed   File "/var/lib/juju/agents/unit-mongodb-0/charm/hooks/hooks.py", line 981, in config_changed
2016-02-03 05:25:17 INFO config-changed     re.MULTILINE).group(1)
2016-02-03 05:25:17 INFO config-changed AttributeError: 'NoneType' object has no attribute 'group'
2016-02-03 05:25:17 ERROR juju.worker.uniter.operation runhook.go:107 hook "config-changed" failed: exit status 1

Any guess is welcome :)

Regards,
Duy

**Comment by derekadams** [comment]
Hi Duy,

It looks like the error you are seeing is in the MongoDB plugin. Our best guess it that their plugin is running into the following error condition:

http://askubuntu.com/questions/630361/juju-quickstart-failed-immediately-with-attributeerror-nonetype-object-has-n

Our JuJu support is not up to date right now, but we are playing catch-up. When we have time to work on the SiteWhere scripts, we will try out the various configurations to make sure they still work. In the meantime, you may want to use our Docker image instead since it's up-to-date with the 1.5.0 release and has more users. See https://hub.docker.com/r/sitewhere/standalone/ for more details.

Thanks,
Derek

**Comment by duybh** [comment]
Hi Derek,

Thank you for your response. Yes, I also come to the same conclusion. However, I'm not experienced enough to modify the code (I don't know how to)

One more question: If I have a customize-able IoT gateway, how can I make it work with Sitewhere in a secured way, not just basic authentication? I think it would be best if there's a function for payload encryption somewhere. Can you kindly show me?

Regards,
Duy

**Comment by garysmi2** [comment]
Depends exactly what your needs are and what exactly you mean.

At the moment we have SiteWhere placed behind SSL terminated nginx, so the sitewhere REST api's aren't accessed directly by "end user" of the web application we are developing. Rather we use Keycloak for user authentication and have nginx redirect to our own Nodejs rest endpoints which use the tokens generated by Keycloak to determine whether to give access or not to a user (all under SSL naturally).  Nodejs then accesses the SiteWhere rest api from behind the proxy using a valid SiteWhere specific user account.  We view users who need to access information via the web application as separate from the users created in Sitewhere who we would consider to be more technical/admin type staff for our needs.

In terms of the data transfer mechanism, you should check what is supported by what you are using,  for example RabbitMQ,  if you want to go the whole hog, has mutual certificate authentication between rabbitmq and the device/agent trying to access the queue.

**Comment by duybh** [comment]
Hi garysmi,

Thank you! It clears out a lot for me. I understand how it works now. Because it trouble me a lot when I think about the security mechanism. Various IoT platform just offer basic authentication. So that's why. 

Do your team have commercial support/training for Sitewhere?

And recently hivemq has gone commercial, so I think people will change to Mosquitto. However I'm not sure about the scalability and short-coming of Mosquitto. Can you give me some suggestion?

Best regards,
Duy

**Comment by garysmi2** [comment]
Hi duybh,

I'm not actually part of Sitewhere so I can not speak on their behalf. I believe however that they do offer commercial support,  The Sitewhere team, Derek et. al. are the ones to contact in regards to this,

Gary.

**Comment by duybh** [comment]
Thanks Garysmi, thanks a lot :)

**Comment by derekadams** [comment]
Hi Duy,

As Gary mentioned, we do offer commercial support and training for SiteWhere. We are in the process of publishing a commercial website at http://www.sitewhere.com, but in the meantime, feel free to contact us at admin@sitewhere.com if you would like more information.

Kind regards,
Derek
