### ISSUE TITLE
Logging in when multiple tenants have been created

### ISSUE THREAD

**Issue by garysmi2** [sitewhere/sitewhere#27]
Hi Derek,

trying out the official download of 1.6.0

Issue:

Create an additional tenant as well as the default one.
Logout and log back in again.
On the tenant selection screen select one.

Results in an error and the message:
"Invalid tenant choice"

I built from source and checked - on the initial selection the correct id for the selected tenant is passed back to the controller. 
However, from logging the output of the loop where chosen is selected it looks like the endpoint is being called multiple times and on every subsequent invocation the tenantId is being passed in as the string "server" and the error message above is the ultimate result.

**Comment by derekadams** [comment]
Hi Gary,

Thanks for reporting the problem. It sounds like a regression introduced by some of the new permissions changes. We will take a look and put out a point release with the fixes.

Thanks,
Derek

**Comment by derekadams** [comment]
We have reproduced the error and created and Jira issue to track it:

https://sitewhere.atlassian.net/browse/SITEWHERE-275

We will create a 1.6.1 point release to address this and any other issues found in the next few days.

Thanks,
Derek

**Comment by derekadams** [comment]
The fix has been checked in to the 1.6.1 branch. In the meantime, you can download a fixed war file at the following URL:

https://s3.amazonaws.com/sitewhere/patches/sitewhere-1.6.0-275/sitewhere.war

Thanks again for reporting the problem!

Derek
