### ISSUE TITLE
processing data in sitewhere and send to device

### ISSUE THREAD

**Issue by sadeqans** [sitewhere/sitewhere#30]
hi guys
i have a Scenario for running a project
i have a Traffic application which that install on a lot of android device, and they send measurements and  location to sitewhere(till here no problem).
now i want to process them(received data from devices) and send All data received last ten minutes to all device. how i can do it?? which external system , i should ingratiate by sitewhere??
how i can send All data received last ten minutes .

**Comment by derekadams** [comment]
There are a couple of ways you can do this with SiteWhere. One approach is to have the device make a call to the REST services at an interval and ask for the last 10 minutes of events. There are REST methods for querying based on time period for both assignments and for sites. See the REST docs for an example:

http://documentation.sitewhere.org/rest/single.html#listMeasurements

 The other approach is to live stream the data to the devices, in which case the 10 minute interval would not apply, but you would always see the latest data. You can use the MQTT outbound processor to send all events to devices that are interested. They just need to subscribe to the topic you broadcast on. See this documentation for more information:

http://documentation.sitewhere.org/userguide/tenant/event-processing.html#mqtt-event-processor

The part about sending all data every 10 minutes would only work with polling, but live streaming would make sure the latest data is always on the client.

**Comment by sadeqans** [comment]
tnx for your response.
but i want use mqtt , and before send data to devices i should process data then send them to devices,
i thinks should use hazelcast, but i don't any idea about hazelcast...
how process data??? how send data from hazelcast to devices???

**Comment by derekadams** [comment]
If you use the approach with the outbound MQTT processor, the data will be processed and then routed to the queue afterward. If you want to use Hazelcast, you would need a device capable of running Java and enough memory (over 400k) to run the Hazelcast client.

**Comment by sadeqans** [comment]
hi again
i know that , but how i can process data in sitewhere before send data by mqtt?? i don't any idea!!!!
and sitewhere explanation is very week (lack of document). 
can i use java project like air-traffic example, for fetch data from mongoDB and process that, then forward data over mqtt to devices?how??

**Comment by sadeqans** [comment]
tnx for your help
could you please help me.now i'm waiting for your response.
do you Any answers for me???

**Comment by derekadams** [comment]
If you are looking to add processing logic before sending data back out over MQTT, take a look at the Raspberry Pi demo which applies conditional logic and creates new events in response to inbound data:

http://documentation.sitewhere.org/tutorials/rpi/node-red-dht11-logic.html

The general flow is:

1. SiteWhere brings in data via event sources.
2. SiteWhere stores data and hands it off to outbound pipeline.
3. Groovy processor applies logic (possibly creates new events or other system objects)
4. MQTT outbound processor (or Hazelcast, etc) sends data to interested parties.

**Comment by sadeqans** [comment]
public class test extends TenantLifecycleComponent {

    private static ISite site;
    private static int maxCount = 100;
    private static DeviceAssignment device;
    private static IDeviceManagement dm;
    private static IDeviceEventManagement dem;
    private static SiteWhereClient siteWhereClient;
    /**
     * Tenant set by event processor
     */
   // private static ITenant tenant;
    private static final String SITE_ID = "1d9e9a2e-4594-44ea-ac02-2e8adcd8f866";
    private static Map<String, String> parameters = new HashMap<String, String>();
    //private static final IDeviceManagement deviceManagement=new DeviceManagementDecorator();
    /**
     * MQTT settings
     */
    private static MQTT mqtt;

    /**
     * MQTT connection
     */
    private static FutureConnection connection;

    /**
     *
     * @param args
     * @throws SiteWhereException
     */
    public static void main(String[] args) throws SiteWhereException {
       // SiteWhere siteWhere=new SiteWhere();
        //  SiteWhere.start();
        siteWhereClient = new SiteWhereClient("http://localhost:8081/sitewhere/api/", "admin", "password");
        System.out.println(siteWhereClient.getTenantAuthToken());
        // SiteWhere.start();
        if (waitForSiteWhereToStart()) {
//        site = siteWhereClient.getSiteByToken(SITE_ID);
            test t = new test(LifecycleComponentType.System);
            t.start();
        }
       // IDeviceManagement dm = SiteWhere.getServer().getDeviceManagement(getTenant());

        DeviceActions deviceActions = new DeviceActions(dm, dem);
        //site = siteWhereClient.getSiteByToken(SITE_ID);
        // DeviceAssignment device = siteWhereClient.getDeviceAssignmentByToken(SITE_ID);
        //  siteWhereClient.createBatchCommandInvocation()

        DeviceLocationSearchResults result = siteWhereClient.listDeviceLocations(SITE_ID, maxCount);

        List<DeviceLocation> locations = result.getResults();
        MqttCommandDestination mqttCommandDestination = new MqttCommandDestination();
       // IDeviceManagement dm = SiteWhere.getServer().

        try {
            MQTT mqtt = new MQTT();
            mqtt.setHost("localhost", 1883);
            connection = mqtt.futureConnection();
            Future<Void> future = connection.connect();
            future.await(3, TimeUnit.SECONDS);
            System.out.println("Connected to: " + mqtt.getHost());
        } catch (URISyntaxException e) {
            throw new RuntimeException(e);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        for (DeviceLocation location : locations) {
            parameters.clear();
            parameters.put("lat", location.getLatitude().toString());
            parameters.put("lng", location.getLongitude().toString());
            parameters.put("speed", "20");
            try {

                deviceActions.sendCommand(location.getDeviceAssignmentToken(), "TrafficData", parameters);
            } catch (Exception e) {
                throw new SiteWhereException("Unable send data", e);
            }
            System.out.println(location.getLatitude());
        }
        if (connection != null) {
            connection.disconnect();
        }
    }

    protected static boolean waitForSiteWhereToStart() {
        while (true) {
            try {
                siteWhereClient.getSiteWhereVersion();
                return true;
            } catch (Throwable e) {
                LOGGER.info("Waiting on SiteWhere REST services to become available.", e);
            }
            try {
                Thread.sleep(5000);
            } catch (InterruptedException e) {
                LOGGER.error("Interrupted while waiting for SiteWhere to start.");
                return false;
            }
        }
    }

    public test(LifecycleComponentType type) {
        super(type);
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.sitewhere.spi.server.lifecycle.ILifecycleComponent#start()
     */
    @Override
    public void start() throws SiteWhereException {
        //ITenantAware ita=new GroovyStreamProcessor();
     //   ITenant tenant1=ita.getTenant();
        ITenant tenant1 = getTenant();
        System.out.println(tenant1);
        dm = SiteWhere.getServer().getDeviceManagement(getTenant());
        dem = SiteWhere.getServer().getDeviceEventManagement(getTenant());
        if (dm == null) {
            throw new SiteWhereException(
                    "Registration manager auto assignment site token is invalid.");
        }

    }

    /*
     * (non-Javadoc)
     * 
     * @see com.sitewhere.spi.server.ITenantAware#getTenant()
     */
    /*
     * (non-Javadoc)
     * 
     * @see com.sitewhere.spi.server.lifecycle.ILifecycleComponent#getLogger()
     */
    @Override
    public Logger getLogger() {
        return LOGGER;
    }
    /*
     * (non-Javadoc)
     * 
     * @see com.sitewhere.spi.server.lifecycle.ILifecycleComponent#stop()
     */

    @Override
    public void stop() throws SiteWhereException {
    }

}

**Comment by derekadams** [comment]
What exactly is the use case you are trying to implement? The code you posted looks like a mix of a few different concepts. 

The use of a main method makes it seem like you are running the code from somewhere other than the server. It also looks like you are connecting via MQTT rather than using REST. The operations available for that scenario are available here:

http://documentation.sitewhere.org/userguide/sending-data.html

If you want to invoke a device command from a device, you would have to use the REST services since it's not supported via MQTT right now. Instead, you would need to make a direct REST call to create a device command invocation as shown here:

http://documentation.sitewhere.org/rest/single.html#createCommandInvocation

You are extending TenantLifecycleComponent which is only intended for internal SiteWhere components running on the server, so nothing related to the lifecycle will work. You also will not have access to SiteWhere.getServer() since that code only works for components running inside SiteWhere itself. From a device standpoint, you should always interact via the protocol, which in this case would be MQTT or REST.

**Comment by sadeqans** [comment]
tnx for response
but this code running on the serever( like AirTaraffic example).
i want send location data which saved on database to devices over Mqtt.but i don't know , where i should set tenant??????getTenant return null..
which class i should extend?

**Comment by sadeqans** [comment]
hi Derek Adams,
how to send processed data to devices through sitewhere?
i dont know how to get tenant?

**Comment by sadeqans** [comment]
hi derekadams
do you have any response for me? because i'm stopped in this state, and waiting for your help.
tanks for your response.
