### ISSUE TITLE
error for listDeviceCommand

### ISSUE THREAD

**Issue by sadeqans** [sitewhere/sitewhere#36]
hi
i want get command from sitewhere then execute this command by bellow code, but this code has error

```

```
 siteWhereClient = new SiteWhereClient("http://localhost:8081/sitewhere/api/","admin","password","sitewhere1234567890");
 com.sitewhere.rest.model.system.Version version=siteWhereClient.getSiteWhereVersion();
 DeviceCommandSearchResults command   =siteWhereClient.listDeviceCommands("d2604433-e4eb-419b-97c7-88efe9b2cd41", true);

```


log output

Exception in thread "main" com.sitewhere.spi.SiteWhereSystemException: Unknown error.
	at com.sitewhere.rest.client.SiteWhereErrorHandler.handleError(SiteWhereErrorHandler.java:53)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:565)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:484)
	at com.sitewhere.rest.client.SiteWhereClient.sendRest(SiteWhereClient.java:970)
	at com.sitewhere.rest.client.SiteWhereClient.listDeviceCommands(SiteWhereClient.java:306)
	at com.tavana.sitewhere.SiteWhereCommand.main(SiteWhereCommand.java:99)

Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project MySiteWhere: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.
For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by sadeqans** [comment]
i used this code but Again, in the last line give error


package com.tavana.sitewhere;

import com.sitewhere.rest.client.SiteWhereClient;
import com.sitewhere.rest.model.device.DeviceSpecification;
import com.sitewhere.rest.model.device.command.DeviceCommand;
import com.sitewhere.rest.model.search.DeviceCommandSearchResults;
import com.sitewhere.spi.SiteWhereException;
import com.sitewhere.spi.device.ISite;
import static com.tavana.sitewhere.SiteWhereCommand.siteWhereClient;

/**
 *
 * @author ansari
 */
public class CommandInvoke {
     private static final String SITE_ID = "bb105f8d-3150-41f5-b9d1-db04965668d3";
     private static final String athen   ="d2604433-e4eb-419b-97c7-88efe9b2cd41";
     public static SiteWhereClient siteWhereClient;
     public static ISite site ;
     public static DeviceSpecification deviceSpecification;
     public static DeviceCommandSearchResults deviceCommand;
     
       /**
     *
     * @param args
     * @throws SiteWhereException
     */
    public static void main(String[] args) throws SiteWhereException {
        
    siteWhereClient = new SiteWhereClient("http://localhost:8081/sitewhere/api/","admin","password","sitewhere1234567890");
    site=siteWhereClient.getSiteByToken(SITE_ID );
    deviceSpecification= siteWhereClient.getDeviceSpecificationByToken(athen);
    deviceCommand= siteWhereClient.listDeviceCommands( deviceSpecification.getToken(), true);
    }
    
}

**Comment by sadeqans** [comment]
i used this code  but again give same error in last line
`package com.tavana.sitewhere;

import com.sitewhere.rest.client.SiteWhereClient;
import com.sitewhere.rest.model.device.DeviceSpecification;
import com.sitewhere.rest.model.device.command.DeviceCommand;
import com.sitewhere.rest.model.search.DeviceCommandSearchResults;
import com.sitewhere.spi.SiteWhereException;
import com.sitewhere.spi.device.ISite;
import static com.tavana.sitewhere.SiteWhereCommand.siteWhereClient;

public class CommandInvoke {
     private static final String SITE_ID = "bb105f8d-3150-41f5-b9d1-db04965668d3";
     private static final String athen   ="d2604433-e4eb-419b-97c7-88efe9b2cd41";
     public static SiteWhereClient siteWhereClient;
     public static ISite site ;
     public static DeviceSpecification deviceSpecification;
     public static DeviceCommandSearchResults deviceCommand;
    public static void main(String[] args) throws SiteWhereException {  
    siteWhereClient = new SiteWhereClient("http://localhost:8081/sitewhere/api/","admin","password","sitewhere1234567890");
    site=siteWhereClient.getSiteByToken(SITE_ID );
    deviceSpecification= siteWhereClient.getDeviceSpecificationByToken(athen);
    deviceCommand= siteWhereClient.listDeviceCommands( deviceSpecification.getToken(), true);
    }
    
}
`

**Comment by derekadams** [comment]
Is there an error message in the SiteWhere log file?

**Comment by anhdenday** [comment]
Hi @derekadams 
I met the same problem, here is my code: 

```
ISiteWhereClient client = new SiteWhereClient("http://sitewhereserveraddress:8080/sitewhere/api/", "admin","password");
// get sitewhere version
		Version v = client.getSiteWhereVersion();
		
		System.out.println("Version Edition Id: " + v.getEditionIdentifier());
		
		DeviceCommandSearchResults command = client.listDeviceCommands("7dfd6d63-5e8d-4380-be04-fc5c73801dfb", true);
		
		List<? extends DeviceCommand> listCommandDevices = command.getResults();
		
		for (DeviceCommand dc: listCommandDevices){
			System.out.println("Command Desc: " + dc.getDescription());
			System.out.println("Command name: " + dc.getName());
		}

```
Here is exception. 
```
DEBUG: org.springframework.web.client.RestTemplate - Created GET request for "http://sitewhereserveraddress:8080/sitewhere/api/system/version"
DEBUG: org.springframework.web.client.RestTemplate - Setting request Accept header to [application/json, application/*+json]
DEBUG: org.springframework.web.client.RestTemplate - GET request for "http://sitewhereserveraddress:8080/sitewhere/api/system/version" resulted in 200 (OK)
DEBUG: org.springframework.web.client.RestTemplate - Reading [class com.sitewhere.rest.model.system.Version] as "application/json;charset=UTF-8" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@57a3af25]
Version Edition Id: CE
DEBUG: org.springframework.web.client.RestTemplate - Created POST request for "http://sitewhereserveraddress:8080/sitewhere/api/specifications/7dfd6d63-5e8d-4380-be04-fc5c73801dfb/commands&includeDeleted=true"
DEBUG: org.springframework.web.client.RestTemplate - Setting request Accept header to [application/json, application/*+json]
DEBUG: org.springframework.web.client.RestTemplate - POST request for "http://sitewhereserveraddress:8080/sitewhere/api/specifications/7dfd6d63-5e8d-4380-be04-fc5c73801dfb/commands&includeDeleted=true" resulted in 404 (Not Found); invoking error handler
Exception in thread "main" com.sitewhere.spi.SiteWhereSystemException: Unknown error.
	at com.sitewhere.rest.client.SiteWhereErrorHandler.handleError(SiteWhereErrorHandler.java:53)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:636)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:592)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:560)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:479)
	at com.sitewhere.rest.client.SiteWhereClient.sendRest(SiteWhereClient.java:970)
	at com.sitewhere.rest.client.SiteWhereClient.listDeviceCommands(SiteWhereClient.java:306)
	at vn.vnpt.iot.m2m.web.service.impl.TestSiteWhere.main(TestSiteWhere.java:38)

```
I've checked in the log file in server and here is the log

```
3:17:42,281 INFO  [ResponseTimerFilter] Call for GET to 'http://sitewhereserveraddress:8080/sitewhere/api/system/version' returned in 1 ms.
23:17:42,398 WARN  [PageNotFound] No mapping found for HTTP request with URI [/sitewhere/api/specifications/7dfd6d63-5e8d-4380-be04-fc5c73801dfb/commands&includeDeleted=true] in DispatcherServlet with name 'rest'
23:17:42,399 INFO  [ResponseTimerFilter] Call for POST to 'http://sitewhereserveraddress:8080/sitewhere/api/specifications/7dfd6d63-5e8d-4380-be04-fc5c73801dfb/commands&includeDeleted=true' returned in 2 ms.

```
Thanks you

**Comment by sadeqans** [comment]
hi derek
no , i run this code in NetBeans(Remote to sitewhere).

**Comment by sadeqans** [comment]
hi @derekadams 
My problem like @anhdenday 
there is no error in log file sitewhere
this error happen in java because i want interact with sitewhere by java code.

**Comment by sadeqans** [comment]
hi guys
i solved that by overrides function listDeviceCommands by method get(this function in SiteWhereClient class used method post for rest )
and my function now working

public class Help extends SiteWhereClient{
	public DeviceCommandSearchResults listDeviceCommands(String specificationToken, boolean includeDeleted)
			throws SiteWhereException {
            Map<String, String> vars = new HashMap<String, String>();
		vars.put("token", specificationToken);
		vars.put("includeDeleted", String.valueOf(includeDeleted));
		return sendRest(DEFAULT_BASE + "specifications/{token}/commands",
				HttpMethod.GET, null, DeviceCommandSearchResults.class, vars);
	}
    
}

**Comment by anhdenday** [comment]
The original one is:

```
public DeviceCommandSearchResults listDeviceCommands(String specificationToken, boolean includeDeleted)
			throws SiteWhereException {
		Map<String, String> vars = new HashMap<String, String>();
		vars.put("token", specificationToken);
		vars.put("includeDeleted", String.valueOf(includeDeleted));
		return sendRest(getBaseUrl() + "specifications/{token}/commands&includeDeleted={includeDeleted}",
				HttpMethod.POST, null, DeviceCommandSearchResults.class, vars);
	}
```
I dont know why if I override listDeviceCommands() method, it's worked but If I modify directly on SiteWhereClient.java (just removed "&includeDeleted={includeDeleted}" ) and after that build sitewhere-client jar file and include this jar file in my project class path it's still not work.
Thanks

**Comment by sadeqans** [comment]
in original request used post, but in override i used request by get and now is that working

**Comment by anhdenday** [comment]
Yes, and if even when using GET but not removed "&includeDeleted={includeDeleted}" it's will not work.

**Comment by sadeqans** [comment]
yes, of course
if you look at to my example, i remove that
