### ISSUE TITLE
Sitewhere installation problem

### ISSUE THREAD

**Issue by sameerbetageri10** [sitewhere/sitewhere#45]
I have set up mongodb server and is up n running and installed the mosquitto MQTT broker. But unable  to access the administartive console of the sitewhere

**Comment by sameerbetageri10** [comment]
unable to access sitewhere admin console at http://localhost:/sitewhere

**Comment by derekadams** [comment]
Which operating system are you using? Also, are you using one of the packaged distributions or building the system yourself? You should be able to download a packaged distribution, unzip/tar it, then run startup.sh/bat. No changes should be required for using Mosquitto instead of HiveMQ. When the system starts, are you seeing any exceptions in the system logs? If so, please attach them and we will take a look.

**Comment by sameerbetageri10** [comment]
i am using windows 7 operating system.
i have performed the operations as follows:
1. run mongo db server.
2. install mosquitto broker
3. download and unzip sitewhere package.
4. run the startup from command prompt
5. sitewhere server has started in ......ms
6. login to sitewhere admin panel through
http://localhost:8080/sitewhere/admin

issue: unable to load the sitewhere admin panel.

i have attached screen shots for ur reference

**Comment by derekadams** [comment]
Are you still having problems with this?

**Comment by sameerbetageri10** [comment]
My problem got solved...may be it was jdk problem...I fixed it by updating
jdk.......can u pls suggest me on how do I connect my cellphone to send
data to sitewhere

**Comment by anhdenday** [comment]
I think it's depend on your purpose. If you want your cellphone is a "things" something like a gateway, you should use "sitewhere-ios-sdk" or "sitewhere-android-sdk" to connect to sitewhere via MQTT. If you want your cellphone is just a client to connect to sitewhere to view the data, you can use rest service. If i have something wrong please correct me @derekadams 
Thanks you and best regards,

**Comment by derekadams** [comment]
Thanks @anhdenday, that is exactly right. If you want to create an application that interacts with SiteWhere, you should use the provided SDKs. If you want to create a web application, use the REST services.

**Comment by anhdenday** [comment]
@derekadams, 
As I see so long time the provided SDKs is not update so it's compatible with the latest version of sitewhere (1.8.0)?

**Comment by derekadams** [comment]
The new 1.8.0 version is backward compatible with the communication protocols used in all of the SDKs. The only SDKs that is known to have issues right now is the one for Arduino since it is using a much earlier version of the protocol.
