### ISSUE TITLE
Sitewhere: Problem with Emulate Assignment (MAP)?

### ISSUE THREAD

**Issue by anhdenday** [sitewhere/sitewhere#46]
Hi @derekadams, 
As I know, Sitewhere is using OpenStreetMap, it's free, but today I dont know why when I access to device assignment to see the Map but it's appear the result as picture bellow.
![7-20-2016 9-47-07 am](https://cloud.githubusercontent.com/assets/6926208/16974376/294c0426-4e66-11e6-99a3-a14072b331fa.png)
I dont have any experience about the Map, could you please take a look and give me any recommand?
Thanks you so much

**Comment by derekadams** [comment]
We have noticed the same problem. The default SiteWhere map provider uses MapQuest and accesses the map tiles directly. They have discontinued access to the map tiles, so we are looking into other options to use instead. We currently support MapQuest and GeoServer, but there are probably some other viable alternatives out there.

**Comment by derekadams** [comment]
We added OpenStreetMap as the default map provider in SiteWhere 1.8.0 and display existing MapQuest maps using OSM for backward compatibility. The 1.8.0 code has been pushed to the master branch and will be officially released shortly.
