### ISSUE TITLE
Problem during deploy sitewhere 1.8 on Ubuntu 14.04!

### ISSUE THREAD

**Issue by anhdenday** [sitewhere/sitewhere#47]
Hi, 
I am build sitewhere 1.8 from the source code, after make tgz file, I extract and run startup.sh like this

tar -zxvf sitewhere-server-1.8.0.tgz
mv sitewhere-server-1.8.0 /opt/sitewhere
export SITEWHERE_HOME=/opt/sitewhere
cd /opt/sitewhere/bin
sh startup.sh 
But it could not run and appear below message on the terminal

```
> freeman@ubuntu01:/opt/sitewhere/bin$ sh startup.sh
> 
>   SiteWhere Start Script for Linux/Unix v1.0
> 
> : not found 5: startup.sh: 
> startup.sh: 52: startup.sh: Syntax error: end of file unexpected (expecting "then")
> freeman@ubuntu01:/opt/sitewhere/bin$ 
```

while I change to sitewhere 1.7.0 it's still ok.

Please take a look

**Comment by derekadams** [comment]
We tested with a clean Ubuntu 14.04 LTS instance in the cloud and were not able to reproduce the problem. Can you try with the version at the following URL and see if you have the same problem?

https://s3.amazonaws.com/sitewhere/sitewhere-server-1.8.0.tgz

Thanks!
Derek

**Comment by anhdenday** [comment]
Hi @derekadams ,
The version on your link is ok. I am using window 8 and build tgz with Cygwin terminal to type the build command. "gradle clean serverTar". 
I will try to try with my mac terminal

**Comment by derekadams** [comment]
Issue #46 should be fixed as of the 1.8.0 release. Are you still seeing the MapQuest tile placeholders on the map screen? Also, do you have an option when editing a site to use OpenStreetMap as the map provider?

**Comment by anhdenday** [comment]
I think it's cached problem or because of somehow it's not updated. Today I've just checked again, the map problem (issue #46) already OK. Next week I will try to build sitewhere server from the source code on Linux Base and deploy again to Ubuntu 14.04 to see the result. I will report to you later
Thanks you for your reply and have a good Sunday :)

**Comment by anhdenday** [comment]
Dear @derekadams, 

I just tried to build on my Mac and deploy on ubuntu server. Everything is OK.
I think the problem is because the last time I build with Cygwin terminal on window.

Thanks you
