### ISSUE TITLE
How to integrate GPS tracker to SiteWhere?

### ISSUE THREAD

**Issue by anhdenday** [sitewhere/sitewhere#49]
Hi @derekadams, 

As I see in Web Admin, SiteWhere support to connect to GPS tracker something like MeiTrack GPS device!!!
Could you please tell me how to connect it to SiteWhere? So that I can get lat, long from it!
Because As I see it's doesn't have the OS. So I could not use the provided Agent! Please give me an advice!
Thanks you so much

**Comment by derekadams** [comment]
Hi @anhdenday,

We have done testing with MeiTrack GPS devices in the past, but there are no examples in the current code base. The general idea is to use a socket event receiver to handle receiving and parsing payloads sent directly to SiteWhere from the device. An example of the general technique is shown in this GitHub repository:

https://github.com/sitewhere/sitewhere-examples/tree/master/socket-event-source/groovy-socket-decoder

Note that the device must be configured to report to the SiteWhere host/port you have set up in the event source. The device will connect via TCP/IP and send a command payload. SiteWhere can parse the command via Groovy script and optionally carry on a conversation with the device before terminating the connection.

Let me know if you have any questions.

Regards,
Derek

**Comment by anhdenday** [comment]
Thanks you for your reply @derekadams , 
I understood the general idea , In fact I don't have MeiTrack GPS device yet therefore I could not test with It.
Actually I want  to buy this one for car tracker: http://www.aliexpress.com/item/TK206-OBD-gps-gsm-gprs-car-tracker-Quad-Band-Anti-theft-GSM-GPRS-Mini-GPS/32363856819.html?spm=2114.01010208.3.10.fEv7jH&ws_ab_test=searchweb201556_7,searchweb201602_2_10057_10056_10055_10049_10059_10058_10017_405_404_10060_10061_10062_412,searchweb201603_1&btsid=80c3d036-022d-4999-8b0a-4b7adf06af71
The parameter I want to parse it is not only the location (lat, long), it's include speed, gasoline, temporary, battery status...
So that if I want to get these parameters I will implement it as following. Please correct me if something is wrong? 
Map<String, Double> measurementsPart = new HashMap<String, Double>();
measurementsPart.put("speed", part[4] );
measurementsPart.put("speed", part[5] );
......
def measurements = new DeviceMeasurementsCreateRequest()
measurements.setMeasurements(measurementsPart);
......
Of course, following your recommendation, it's just only the idea that I will do, Actually I dont have the device yet. 

Thanks you so much

**Comment by derekadams** [comment]
You will need to download the operation manual for the device and confirm how it connects and what the message payloads look like. Most of these types of devices use similar payloads, but each has its own nuances. Once you have the device and point it to SiteWhere, you should be able to see what it sends and update the script accordingly.

**Comment by anhdenday** [comment]
Yes, my example code is assuming that the format of message payloads is look like the message payloads in GitHub repository like that you already mentioned above. 
I will order one device and check the manual how it connects then try to point to sitewhere and will update the script to match the real message payload format.
