### ISSUE TITLE
How to understand asset management?

### ISSUE THREAD

**Issue by marsprobe** [sitewhere/sitewhere#50]
Hi @derekadams,

I have installed sitewhere and downloaded the source code. While I have questions about asset management module.

1. Are the items in Default Device Management (fs-devices) asset category? If not, why is a device specification associated with one item in fs-devices?

2.Are the items in fs-hardware or fs-persons asset instance instead of asset category?

I am puzzled how to understand it. Hope you gives answers.

**Comment by derekadams** [comment]
There are currently four types of asset categories: device, person, hardware, and location. When creating a device specification, you can choose from any of the asset categories that contain devices. You can also add a new category or add devices to the existing fs-devices category if needed. 

The other category types are used for device assignments. You can associate any type of asset with an existing device to model a relationship in the real world. For instance: badge -> person it is assigned to, heart monitor -> hospital ward, tracking device -> heavy equipment asset.
