### ISSUE TITLE
why this project build war but run use java -jar

### ISSUE THREAD

**Issue by defshine** [sitewhere/sitewhere#51]
I can't run this project in idea, but can run it through startup.bat script.
See this:
java %JAVA_OPTS% %JPDA_OPTS% -jar %SITEWHERE_FOLDER%/lib/sitewhere.war
this war can't run in tomcat because it include some tomcat and servlet api
why don't build project to a jar for running?

**Comment by derekadams** [comment]
As of version 1.7.0, SiteWhere uses Spring Boot as its deployment mechanism, which means that an embedded version of Tomcat is included in the SiteWhere distribution. We chose this strategy to allow more control over the environment in which SiteWhere runs and take advantage of the infrastructure that Spring Boot provides. Even though the artifact has a "war" suffix, it is treated as an executable jar which uses the Spring Boot loader to bootstrap the application. There is some support for traditional deployments in Spring Boot (http://docs.spring.io/spring-boot/docs/current/reference/html/howto-traditional-deployment.html), but we do not use that approach.

**Comment by defshine** [comment]
Thanks for reply!
I just want to run/debug this project in intellij idea
For normal spring boot web app,I can directly run the main class by click the Run button.
But for sitewhere, I find the files under webapp will not be builded for running, especially the jsp files.
I really want to know how to run sitewhere in idea

**Comment by hongqizhang** [comment]
Me too.  It is not conveninent to launch the jar everytime after building with gradlew.  Perhaps, there are also some other methods, please help us.

**Comment by anhdenday** [comment]
So long time I did not debug sitewhere server on the IDE but I think you can refer to my issue #39 . Here is my solution that worked before when I using sitewhere server 1.7
I've temporary hard code SITEWHERE_HOME at "getGlobalConfigurationFolder()" method on the class  DefaultGlobalConfigurationResolver and copy the pre-configured of "conf" folder to $SITEWHERE_HOME/conf and run with Intelij Idea with no error. 
https://cloud.githubusercontent.com/assets/6926208/15236883/5bbc09ea-18f3-11e6-81d3-8d85115ab5d6.png.

**Comment by defshine** [comment]
@anhdenday 
thank you~
I can setup it in idea, only the admin ui has problem, the rest api is ok.
You needn't hard code ,  set jvm args in idea works fine.For example:
-Dsitewhere.home={your dir}

**Comment by anhdenday** [comment]
In the terminal of Intellij Idea. Try to run "gradle bootRun" instead of running main class of SiteWhereWebApplication, lasttime it's worked for me
