### ISSUE TITLE
Creating new alert via REST APIs not working anymore

### ISSUE THREAD

**Issue by amrdruid** [sitewhere/sitewhere#512]
Hello there !

Yesterday I was creating alerts on SiteWhere via the REST apis with no problem. 

Today when I tried to send the same data with the same structure but now I get a 400 error, that states that **No body content passed for POST request** 

I tried the same example that you have in the rest documentation 

```
{
  "eventDate" : "2016-12-10T13:11:46.213-0500",
  "updateState" : true,
  "source" : "testing-device_002",
  "level" : "Warning",
  "type" : "engine.overheat",
  "message" : "Engine temperature is at top of operating range."
}
```

I have the assignment token in the URL, I also have Authorization, Content type:application/json, and the X-SiteWhere-Tenant in the headers along with the basic auth

Thanks in advance !

**Comment by derekadams** [comment]
Try sending the payload with "Device" as the value for "source". The source field indicates whether an alert was generated by the device or as the result of system processing. The hardware id of the device is derived from the assignment token you passed in the URL, so you do not need to pass it in the payload. Hope that helps!

**Comment by amrdruid** [comment]
It works, thanks alot !
