### ISSUE TITLE
Response for preflight has invalid HTTP status code 401

### ISSUE THREAD

**Issue by AkhilRam7** [sitewhere/sitewhere#519]
This code worked before for me now i am left out with this error ,any help

`<script>
function loadDoc() {
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      console.log(responseText);
    }
  };
  xhttp.open("GET", "http://localhost:8080/sitewhere/api/assets/categories/fs-devices/assets", true);
  xhttp.setRequestHeader("Content-Type","text/plain");
  xhttp.setRequestHeader("Authorization", "Basic YWRtaW46cGFzc3dvcmQ=");
  xhttp.setRequestHeader("X-Sitewhere-Tenant","sitewhere1234567890");
  xhttp.send(null);
}
</script>`

**Comment by derekadams** [comment]
Is there an error message in the server log?

**Comment by AkhilRam7** [comment]
There is no error from the code
![screenshot from 2017-07-11 21-25-17](https://user-images.githubusercontent.com/18403393/28013967-8b68c4b6-6588-11e7-8cb6-e363bf184668.png)

**Comment by derekadams** [comment]
Are you saying there is no error shown in the "sitewhere.log" file on the server? If you can forward the log file, we will take a look. Also, was the same call working in a previous version of SiteWhere and is now failing after an upgrade, or did something else change?

**Comment by AkhilRam7** [comment]
This is the error in the log
The same worked without upgrading the sitewhere 


2017-07-10 04:11:05,110 WARN  [MulticastService]  [192.168.43.54]:5702 [default] [3.5.4] You probably have too long Hazelcast configuration!
java.io.IOException: Invalid argument (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at com.hazelcast.cluster.impl.MulticastService.send(MulticastService.java:184)
	at com.hazelcast.cluster.impl.MulticastJoiner.searchForOtherClusters(MulticastJoiner.java:112)
	at com.hazelcast.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:48)
	at com.hazelcast.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:38)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)

**Comment by derekadams** [comment]
That exception appears to be related to Hazelcast communication, but I'm not sure that this exception would prevent the server from starting. Are you running multiple SiteWhere instances on the same network? Also, it would help to see the full log file to better understand the issue (unless it contains private information you can not share).

**Comment by derekadams** [comment]
We are not able to replicate the problem. Included is a screenshot of running the same query from the Firefox REST client with the same settings you are using. Verify that you are using the "GET" method and no other errors are showing up in the logs.

![image](https://user-images.githubusercontent.com/338921/28032500-b9cfa848-6578-11e7-9435-83f31c96ba63.png)

**Comment by AkhilRam7** [comment]
I am successful in running the code in POSTMAN similar as RESTClient, Even i am getting it from Curl and Shell too. But i cant find the problem when i use it with javascript and jquery. I am sure that there are no multiple instances of sitewhere.
[sitewhere.log.tar.gz](https://github.com/sitewhere/sitewhere/files/1137774/sitewhere.log.tar.gz)

**Comment by derekadams** [comment]
Here is the JavaScript used in the SiteWhere administrative application:

```
	return jQuery.ajax({
		'type' : 'GET',
		'url' : url,
		'contentType' : 'application/json',
		'async' : false,
		'headers' : {
			"Authorization" : "Basic " + basicToken,
			"X-SiteWhere-Tenant" : tenantToken
		},
		'success' : onSuccess,
		'error' : onFail
	});
```

**Comment by AkhilRam7** [comment]
i have done but i couldnt get the required result
![screenshot from 2017-07-11 11-36-31](https://user-images.githubusercontent.com/18403393/28053318-68c47b8a-662d-11e7-8b14-93044ae3ff35.png)

**Comment by derekadams** [comment]
I just now noticed in the log file that you are running SiteWhere 1.7. Support for CORS was not added until SiteWhere 1.8, which is the reason your request fails (since it is apparently being accessed by an application that is not on the same server/port as SiteWhere). If you upgrade to a recent version, the problem should go away.

**Comment by AkhilRam7** [comment]
Thank you @derekadams  

I just upgrades and CORS problem was solved
