### ISSUE TITLE
Command in JSON format

### ISSUE THREAD

**Issue by rajeshsola** [sitewhere/sitewhere#522]
I am not able to received invoked commands in JSON format through MQTT subscribe using the topic name SiteWhere/commands/%s as mentioned in http://documentation.sitewhere.io/userguide/sending-data.html, I think payload is coming in binary encoding, tried certain tenant configuration options like Command Destination...can some one confirm whether it's a bug in SiteWhere command delivery or some specific tenant configuration is required.

**Comment by derekadams** [comment]
The first thing to check is which command destination is being used based on routing rules. By default, there is a specification mapping router that does a direct mapping of a device specification to a command destination. Verify which command destination your specification routes to in **Device Communication > Device Command Routing > Specification Mapping Router**:

![image](https://user-images.githubusercontent.com/338921/28549628-54079d36-70a9-11e7-9e14-22c4f5b7bd9d.png)

After that, take a look at the command destination and check which command encoder is being used. If you are expecting a JSON payload, the JSON Command Encoder should be used:

![image](https://user-images.githubusercontent.com/338921/28549687-cbb48c86-70a9-11e7-8469-98f1fe8be412.png)

The default setting if there is no mapping for a specification is to use Groovy Protocol Buffers Command Encoder, which contains binary data.

**Comment by rajeshsola** [comment]
Thank you derek...problem got resolved,able to get JSON payloads now.
