### ISSUE TITLE
Access the sitehere Api at sitewhere/api

### ISSUE THREAD

**Issue by sameerbetageri** [sitewhere/sitewhere#53]
Hi i am unable to run http://localhost:8080/sitewhere/api . i have sitewhere server up and running and can even access http://localhost:8080/sitewhere/admin

I have included repository from github in my eclipse but unable to run api request. pls help

**Comment by derekadams** [comment]
You should be able to access the Swagger application for testing REST services at the following URL:

[http://localhost:8080/sitewhere/](http://localhost:8080/sitewhere/)

Note that the URL ending in *api* is the actual endpoint where the REST messages are sent.
