### ISSUE TITLE
are there any documentation of version 2.0.0

### ISSUE THREAD

**Issue by crackwei** [sitewhere/sitewhere#544]
hello,i'm an C++ programmer,and ourteam want to develop something base on sitewhere,but it's java.we found the frame of version 2.0 is perfect.but  it's very difficult to deploy to us.so my problem is:are there any documentation of version 2.0.0?

**Comment by derekadams** [comment]
SiteWhere 2.0.0 is not officially released yet, so we would not advise trying to deploy it until the code is considered stable. The new 2.0 architecture is a complete redesign of the 1.x architecture using a microservices approach and a much more robust processing infrastructure. We are planning to release an early access (EA) version on the week of 11/10/2017, which will include working versions of most of the core microservices. We will then have release candidate (RC) versions every two weeks until the system is considered feature-complete and stable. Part of the RC process will be developing complete guides for all aspects of the system. The current plan is to release the GA version of SiteWhere 2.0 in Q1 2018, though you should be able to start working with it within 4-6 weeks. We appreciate your patience!

**Comment by crackwei** [comment]
OK,thank you.

**Comment by derekadams** [comment]
We have started releasing documentation for the early access releases of the product. You can find the latest documentation here: http://sitewhere.io/docs/en/2.0.EA2/index.html

**Comment by derekadams** [comment]
The updated location for the 2.0.0 documentation is:
https://sitewhere.io/docs/2.0.0/

**Comment by crackwei** [comment]
tthank you.
