### ISSUE TITLE
Error occurs, when importing sitewhere 1,12.0

### ISSUE THREAD

**Issue by erliuwang** [sitewhere/sitewhere#545]
I am deploying sitewhere to windows 10.  the project is imported  from GitHub using Git in Eclipse. The procedure “Install Gradle and Build Projects” is down. According to the procedure s here (http://documentation.sitewhere.io/developer.html)
The errors are listed as below.
![default](https://user-images.githubusercontent.com/33246001/32781784-38cb3240-c981-11e7-81ba-d679d39f2d67.png)

**Comment by derekadams** [comment]
It looks like you only imported one module and not the entire project. The top-level "sitewhere" project is what you should import. If you import using the "Import Gradle Project" wizard, Eclipse should automatically create subprojects for all of the modules and everything will resolve correctly.

**Comment by erliuwang** [comment]
what's the procedures to import the whole project?
I follow the procedures here (http://documentation.sitewhere.io/developer.html)
Isn't it right???

**Comment by derekadams** [comment]
Based on the screenshot, it looks like you only imported "sitewhere-spring-spi" rather than the entire project. You can import it again by deleting the project (choose not to delete underlying resources), then choose "Import -> Import Gradle Project" and choose the SiteWhere root folder.

**Comment by erliuwang** [comment]
"the SiteWhere root folder" refers to the folder "" which is downloaded from the github?

**Comment by derekadams** [comment]
Yes, that is correct.

**Comment by erliuwang** [comment]
OK,thank you very much. Maybe you guys should update the official documents (http://documentation.sitewhere.io/developer.html)

**Comment by derekadams** [comment]
Yes, we are behind on documentation updates. We will be releasing SiteWhere 2.0 as an early access release in the next few weeks. It has a new architecture and will have an updated set of documentation with better formatting and organization.
