### ISSUE TITLE
The tenant id exhibition problem in the beta version 2.0

### ISSUE THREAD

**Issue by erliuwang** [sitewhere/sitewhere#547]
we logged in the beta 2.0, and set up another tenant id. but, the new tenant can not appear.  we changed to log in the 1.12.0, the new tenant can be seen. why the new tenant does not show in the beta version?

**Comment by derekadams** [comment]
We have not officially released SiteWhere 2.0 for beta yet, so there are still many issues. We are hoping to make an "early access" release available by 12/1, but it will still be considered alpha quality. The current plan is to release the official SiteWhere 2.0 GA in early Q1 2018 after we have had time to test, improve performance, and add a few new features.

**Comment by derekadams** [comment]
This should be fixed in 2.0 EA1
