### ISSUE TITLE
how to connect to the SiteWhere server with existing devices using modbus protocol or custom TCP/UDP  

### ISSUE THREAD

**Issue by erliuwang** [sitewhere/sitewhere#548]
The documents in our website recommend  several popular device platforms,such as Android Development Kit, Arduino Development Kit and Raspberry Pi Tutorials.
I'm confused how to access the SiteWhere using existing devices or IoT gateway without changing the existing communication mode. 
For example, how to interact with an intelligent water meter using modbus protocol  or custom TCP/UDP  ?
Or, How to interact with an device transport unit(DTU) which manages several smart sensors ?

**Comment by derekadams** [comment]
The Android, Arduino, and Raspberry Pi development kits all communicate using protocol buffer messages over MQTT. In your case, you would want to directly connect via a TCP socket and handle the bi-directional communication via a Groovy script. We are working on updated documentation for developing custom TCP socket decoders, but it will be a couple of weeks before the new docs are available. They will be part of the SiteWhere 2.0 release candidate, which is due by the end of the year.

**Comment by erliuwang** [comment]
@derekadams Thank you very much. good luck ！
