### ISSUE TITLE
tenant default config of event sources

### ISSUE THREAD

**Issue by defshine** [sitewhere/sitewhere#57]
Event sources include the mqtt topic,default topic is same for every new tenant, such as "SiteWhere/input/protobuf".
If tenant user don't change this topic,  then each tenant subscribe the some topic, so the message will be process by many tenant.

Is it necessary to add special rules for the default topic to distinguish the different tenant ?

**Comment by derekadams** [comment]
There are a few solutions to this problem. One option is to manually update the MQTT topic name on the event source for each tenant you add to the system. Another option is to have a separate MQTT broker for each tenant and update the hostname on a per-tenant basis. Both of these options obviously require manual configuration for each tenant. 

Another more comprehensive approach is to update the tenant template to automatically use the tenant id as part of the MQTT topic. For instance, if you update the **conf/tenant-template/sitewhere.tenant.xml** file and change the topic for the JSON batch topic to be **SiteWhere/input/${tenant.id}/jsonbatch**, each new tenant will automatically get its own queue based on its unique id.
