### ISSUE TITLE
Gps tracking device integration

### ISSUE THREAD

**Issue by presidentpatel** [sitewhere/sitewhere#58]
Hello, do you have any God tracker integration and ready to test or use ?

**Comment by derekadams** [comment]
We do not have a preferred off-the-shelf solution, but SiteWhere can integrate with most existing GPS hardware devices. For instance, we have integrated with MeiTrack devices such as the MT-88 (http://www.globalsources.com/trdshw/DownloadAttachment?attach_id=7158926) and MT-90 (http://www.meitrack.com/en/mt90/). We also support tracking via Android applications or integration with third-party platforms that gather the data and forward it to SiteWhere.

**Comment by presidentpatel** [comment]
Hi Derek, Thanx for quick response . Can you share code url so I can check same and try to integrate my devices also as well I also want to integrate lora gateway so would like to connect over Skype or LinkedIn.
Regards,
Vipul
