### ISSUE TITLE
What does the streaming media module do?

### ISSUE THREAD

**Issue by erliuwang** [sitewhere/sitewhere#586]
![wechat image_20180322094432](https://user-images.githubusercontent.com/33246001/37861652-387633fe-2f79-11e8-9b33-87bbc22f1fb6.png)
What does the streaming media module do?  The service streaming media module is used to access various kinds of cameras or not? 
what time do you  plan to develop the service streaming media  module ? Because it is empty.

**Comment by derekadams** [comment]
Yes, the streaming media microservice will provide a data model and APIs for handling audio/video information. Currently, some of those APIs are contained in the device management microservice and we will have to move them over before 2.0 is released. The current support is limited to a basic data model that allows you to create streams and add/read data from them. The longer-term plan is to add more direct support for specific streaming technologies.

**Comment by erliuwang** [comment]
@derekadams 
how about the streaming media module? Could this module access the camera image data?
