### ISSUE TITLE
Map Not Displaying

### ISSUE THREAD

**Issue by presidentpatel** [sitewhere/sitewhere#59]
Hi,
Please Check Map is not displaying ... in edit site... and how to add custom map type ? like Google Map or Openstreet Map API..?

![sitwhr](https://cloud.githubusercontent.com/assets/8477113/18470530/9c062570-79ca-11e6-9f0f-a57b50bf3763.png)

**Comment by freemannguyen** [comment]
This issue is fixed by Sitewhere 1.8. Which version of sitehwere are you using?

**Comment by presidentpatel** [comment]
Ahh..This is SiteWhere 1.7.0 CE...

I Installed this today only... now how to upgrade it to 1.8 ?

**Comment by defshine** [comment]
here: https://github.com/sitewhere/sitewhere/releases

Also you can download source code and build it by youself
