### ISSUE TITLE
Error occurs, when create Event Source in sitewhere 1.13.0 and sitewhere 1.14.0 and

### ISSUE THREAD

**Issue by erliuwang** [sitewhere/sitewhere#592]
![cu0wu2](https://user-images.githubusercontent.com/33246001/38596809-306d526c-3d86-11e8-9529-1499a4d78362.png)
![cu0wu1](https://user-images.githubusercontent.com/33246001/38596925-08c16964-3d87-11e8-922f-3534bc3586e4.png)

I create a socket Event Source in sitewhere 1.13.0 and sitewhere 1.14.0 and using  the next-generation SiteWhere UI. The errors occurs in sitewhere-tenant.xml file. Then the tenant is down!

**Comment by derekadams** [comment]
Unfortunately, there are quite a few bugs in the beta interface introduced in the 1.x line of products. The best choice for now is to use the standard interface instead. The beta interface has been used as the basis for the interface in SiteWhere 2.0, so all bug fixes and new work on the user interface is being done there.
