### ISSUE TITLE
 Support jCasbin as the authorization backend

### ISSUE THREAD

**Issue by veotax** [sitewhere/sitewhere#603]
[jCasbin](https://github.com/casbin/jcasbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.
4. multiple models like ACL, BLP, RBAC, ABAC, RESTful are supported.

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

I saw there's a RBAC need here, and I think jCasbin is a good choice. What do you think? Thanks.

**Comment by derekadams** [comment]
We will definitely take a look at this for the upcoming SiteWhere 2.0 release. We were already planning to refactor some of the user management features, so this may be a good way to accelerate the process and add richer functionality. Thanks!

**Comment by derekadams** [comment]
We ended up going with an integration with https://syncope.apache.org/ for the short term, but we may also support Casbin as an alternative user management implementation down the road.
