### ISSUE TITLE
Error occurs when execute "gradlew clean dockerImage"

### ISSUE THREAD

**Issue by erliuwang** [sitewhere/sitewhere#609]
log files 👍

C:\Users\WDH\Desktop>echo on

C:\Users\WDH\Desktop>E:

E:\>cd Sitewhere\sitewhere

E:\Sitewhere\sitewhere>gradlew clean dockerImage

> Task :sitewhere-grpc-model:generateProto UP-TO-DATE
Using TaskInputs.file() with something that doesn't resolve to a File object has been deprecated and is scheduled to be removed in Gradle 5.0. Use TaskInputs.files() instead.

> Task :sitewhere-grpc-model:compileJava

> Task :sitewhere-hbase:compileJava

> Task :service-asset-management:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-asset-management\build\docker'.
Using tag 'docker.io/sitewhere/service-asset-management:2.0.ea1' for image.

Step 1/5 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/5 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Running in 9cf555c92dda
Removing intermediate container 9cf555c92dda
---> 74ae14138418
Step 3/5 : EXPOSE 8080

---> Running in 333a3bc6947f
Removing intermediate container 333a3bc6947f
---> 42564a08c0ed
Step 4/5 : COPY service-asset-management-2.0.ea1.jar /

---> ebf9dc2a330e
Step 5/5 : CMD ["java", "-Xmx768m", "-jar", "/service-asset-management-2.0.ea1.jar"]

---> Running in 5b2efdb11dd8
Removing intermediate container 5b2efdb11dd8
---> 2689750d7ee0
Successfully built 2689750d7ee0
Successfully tagged sitewhere/service-asset-management:2.0.ea1

> Task :service-asset-management:dockerImage
Created image with ID '2689750d7ee0'.

> Task :service-batch-operations:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-batch-operations\build\docker'.
Using tag 'docker.io/sitewhere/service-batch-operations:2.0.ea1' for image.

Step 1/5 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/5 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/5 : EXPOSE 8080

---> Using cache
---> 42564a08c0ed
Step 4/5 : COPY service-batch-operations-2.0.ea1.jar /

---> b3c8cb4b048a
Step 5/5 : CMD ["java", "-Xmx768m", "-jar", "/service-batch-operations-2.0.ea1.jar"]

---> Running in ac781d554c2b
Removing intermediate container ac781d554c2b
---> b35043af8d97
Successfully built b35043af8d97
Successfully tagged sitewhere/service-batch-operations:2.0.ea1

> Task :service-batch-operations:dockerImage
Created image with ID 'b35043af8d97'.

> Task :service-command-delivery:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-command-delivery\build\docker'.
Using tag 'docker.io/sitewhere/service-command-delivery:2.0.ea1' for image.

Step 1/5 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/5 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/5 : EXPOSE 8080

---> Using cache
---> 42564a08c0ed
Step 4/5 : COPY service-command-delivery-2.0.ea1.jar /

---> e06ac27050fd
Step 5/5 : CMD ["java", "-Xmx768m", "-jar", "/service-command-delivery-2.0.ea1.jar"]

---> Running in e3069a43b25e
Removing intermediate container e3069a43b25e
---> 76116caacee5
Successfully built 76116caacee5
Successfully tagged sitewhere/service-command-delivery:2.0.ea1

> Task :service-command-delivery:dockerImage
Created image with ID '76116caacee5'.

> Task :service-device-management:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-device-management\build\docker'.
Using tag 'docker.io/sitewhere/service-device-management:2.0.ea1' for image.

Step 1/4 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/4 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/4 : COPY service-device-management-2.0.ea1.jar /

---> 0020cbef5ec9
Step 4/4 : CMD ["java", "-Xmx768m", "-jar", "/service-device-management-2.0.ea1.jar"]

---> Running in 738cd4f36e69
Removing intermediate container 738cd4f36e69
---> 1e1377a27418
Successfully built 1e1377a27418
Successfully tagged sitewhere/service-device-management:2.0.ea1

> Task :service-device-management:dockerImage
Created image with ID '1e1377a27418'.

> Task :service-device-registration:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-device-registration\build\docker'.
Using tag 'docker.io/sitewhere/service-device-registration:2.0.ea1' for image.

Step 1/4 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/4 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/4 : COPY service-device-registration-2.0.ea1.jar /

---> f1784b2aec25
Step 4/4 : CMD ["java", "-Xmx768m", "-jar", "/service-device-registration-2.0.ea1.jar"]

---> Running in ca924e6b920c
Removing intermediate container ca924e6b920c
---> 6b70f6a4076f
Successfully built 6b70f6a4076f
Successfully tagged sitewhere/service-device-registration:2.0.ea1

> Task :service-device-registration:dockerImage
Created image with ID '6b70f6a4076f'.

> Task :service-event-management:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-event-management\build\docker'.
Using tag 'docker.io/sitewhere/service-event-management:2.0.ea1' for image.

Step 1/4 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/4 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/4 : COPY service-event-management-2.0.ea1.jar /

---> 05815a3f7b7c
Step 4/4 : CMD ["java", "-Xmx768m", "-jar", "/service-event-management-2.0.ea1.jar"]

---> Running in c6df521ae56a
Removing intermediate container c6df521ae56a
---> 1163244416d7
Successfully built 1163244416d7
Successfully tagged sitewhere/service-event-management:2.0.ea1

> Task :service-event-management:dockerImage
Created image with ID '1163244416d7'.

> Task :service-event-search:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-event-search\build\docker'.
Using tag 'docker.io/sitewhere/service-event-search:2.0.ea1' for image.

Step 1/4 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/4 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/4 : COPY service-event-search-2.0.ea1.jar /

---> 5b6b9b386fd3
Step 4/4 : CMD ["java", "-Xmx768m", "-jar", "/service-event-search-2.0.ea1.jar"]

---> Running in 84ed6e53ae20
Removing intermediate container 84ed6e53ae20
---> 3054414be24e
Successfully built 3054414be24e
Successfully tagged sitewhere/service-event-search:2.0.ea1

> Task :service-event-search:dockerImage
Created image with ID '3054414be24e'.

> Task :service-event-sources:compileJava
注: E:\Sitewhere\sitewhere\service-event-sources\src\main\java\com\sitewhere\sources\mqtt\MqttCallbackInboundEventReceiver.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

> Task :service-event-sources:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-event-sources\build\docker'.
Using tag 'docker.io/sitewhere/service-event-sources:2.0.ea1' for image.

Step 1/4 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/4 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/4 : COPY service-event-sources-2.0.ea1.jar /

---> 56e594f463a6
Step 4/4 : CMD ["java", "-Xmx768m", "-jar", "/service-event-sources-2.0.ea1.jar"]

---> Running in fd490dd2e99f
Removing intermediate container fd490dd2e99f
---> 48d0a93e7052
Successfully built 48d0a93e7052
Successfully tagged sitewhere/service-event-sources:2.0.ea1

> Task :service-event-sources:dockerImage
Created image with ID '48d0a93e7052'.

> Task :service-inbound-processing:compileJava
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

> Task :service-inbound-processing:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-inbound-processing\build\docker'.
Using tag 'docker.io/sitewhere/service-inbound-processing:2.0.ea1' for image.

Step 1/4 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/4 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/4 : COPY service-inbound-processing-2.0.ea1.jar /

---> 72fe75fb2f09
Step 4/4 : CMD ["java", "-Xmx768m", "-jar", "/service-inbound-processing-2.0.ea1.jar"]

---> Running in e6f91c488785
Removing intermediate container e6f91c488785
---> 672cc157a266
Successfully built 672cc157a266
Successfully tagged sitewhere/service-inbound-processing:2.0.ea1

> Task :service-inbound-processing:dockerImage
Created image with ID '672cc157a266'.

> Task :service-instance-management:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-instance-management\build\docker'.
Using tag 'docker.io/sitewhere/service-instance-management:2.0.ea1' for image.

Step 1/5 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/5 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/5 : COPY service-instance-management-2.0.ea1.jar /

---> e3d714b3e6ad
Step 4/5 : COPY templates /templates

---> ea12cac1eaf0
Step 5/5 : CMD ["java", "-Xmx768m", "-jar", "/service-instance-management-2.0.ea1.jar"]

---> Running in 16eaeac6e386
Removing intermediate container 16eaeac6e386
---> 4e7521737497
Successfully built 4e7521737497
Successfully tagged sitewhere/service-instance-management:2.0.ea1

> Task :service-instance-management:dockerImage
Created image with ID '4e7521737497'.

> Task :service-label-generation:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-label-generation\build\docker'.
Using tag 'docker.io/sitewhere/service-label-generation:2.0.ea1' for image.

Step 1/4 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/4 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/4 : COPY service-label-generation-2.0.ea1.jar /

---> 70bb2528d1f1
Step 4/4 : CMD ["java", "-Xmx768m", "-jar", "/service-label-generation-2.0.ea1.jar"]

---> Running in 9925f4dd7e8f
Removing intermediate container 9925f4dd7e8f
---> 27fb06462298
Successfully built 27fb06462298
Successfully tagged sitewhere/service-label-generation:2.0.ea1

> Task :service-label-generation:dockerImage
Created image with ID '27fb06462298'.

> Task :service-outbound-connectors:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-outbound-connectors\build\docker'.
Using tag 'docker.io/sitewhere/service-outbound-connectors:2.0.ea1' for image.

Step 1/4 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/4 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/4 : COPY service-outbound-connectors-2.0.ea1.jar /

---> 8af0cf20b353
Step 4/4 : CMD ["java", "-Xmx768m", "-jar", "/service-outbound-connectors-2.0.ea1.jar"]

---> Running in 64cdf5f5e6aa
Removing intermediate container 64cdf5f5e6aa
---> 841e466e272d
Successfully built 841e466e272d
Successfully tagged sitewhere/service-outbound-connectors:2.0.ea1

> Task :service-outbound-connectors:dockerImage
Created image with ID '841e466e272d'.

> Task :service-presence-management:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-presence-management\build\docker'.
Using tag 'docker.io/sitewhere/service-presence-management:2.0.ea1' for image.

Step 1/4 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/4 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/4 : COPY service-presence-management-2.0.ea1.jar /

---> 53c2498e5688
Step 4/4 : CMD ["java", "-Xmx768m", "-jar", "/service-presence-management-2.0.ea1.jar"]

---> Running in 5dc6c04f653f
Removing intermediate container 5dc6c04f653f
---> b91fbff50f81
Successfully built b91fbff50f81
Successfully tagged sitewhere/service-presence-management:2.0.ea1

> Task :service-presence-management:dockerImage
Created image with ID 'b91fbff50f81'.

> Task :service-rule-processing:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-rule-processing\build\docker'.
Using tag 'docker.io/sitewhere/service-rule-processing:2.0.ea1' for image.

Step 1/4 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/4 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/4 : COPY service-rule-processing-2.0.ea1.jar /

---> 308bb744f549
Step 4/4 : CMD ["java", "-Xmx768m", "-jar", "/service-rule-processing-2.0.ea1.jar"]

---> Running in 10fe3694d6de
Removing intermediate container 10fe3694d6de
---> f0411b93d924
Successfully built f0411b93d924
Successfully tagged sitewhere/service-rule-processing:2.0.ea1

> Task :service-rule-processing:dockerImage
Created image with ID 'f0411b93d924'.

> Task :service-schedule-management:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-schedule-management\build\docker'.
Using tag 'docker.io/sitewhere/service-schedule-management:2.0.ea1' for image.

Step 1/4 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/4 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/4 : COPY service-schedule-management-2.0.ea1.jar /

---> 30aa85b4e00c
Step 4/4 : CMD ["java", "-Xmx768m", "-jar", "/service-schedule-management-2.0.ea1.jar"]

---> Running in 12cf788f623e
Removing intermediate container 12cf788f623e
---> 99986d5819ff
Successfully built 99986d5819ff
Successfully tagged sitewhere/service-schedule-management:2.0.ea1

> Task :service-schedule-management:dockerImage
Created image with ID '99986d5819ff'.

> Task :service-streaming-media:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-streaming-media\build\docker'.
Using tag 'docker.io/sitewhere/service-streaming-media:2.0.ea1' for image.

Step 1/4 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/4 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/4 : COPY service-streaming-media-2.0.ea1.jar /

---> 67a825aff6ef
Step 4/4 : CMD ["java", "-Xmx768m", "-jar", "/service-streaming-media-2.0.ea1.jar"]

---> Running in 0e2059ab172f
Removing intermediate container 0e2059ab172f
---> 6c4e4db9d7a3
Successfully built 6c4e4db9d7a3
Successfully tagged sitewhere/service-streaming-media:2.0.ea1

> Task :service-streaming-media:dockerImage
Created image with ID '6c4e4db9d7a3'.

> Task :service-tenant-management:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-tenant-management\build\docker'.
Using tag 'docker.io/sitewhere/service-tenant-management:2.0.ea1' for image.

Step 1/5 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/5 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/5 : COPY service-tenant-management-2.0.ea1.jar /

---> 8ce1dd21677a
Step 4/5 : COPY templates /templates

---> 5fc6dd99ded9
Step 5/5 : CMD ["java", "-Xmx768m", "-jar", "/service-tenant-management-2.0.ea1.jar"]

---> Running in cc38c2487bd2
Removing intermediate container cc38c2487bd2
---> e3f3d3baae05
Successfully built e3f3d3baae05
Successfully tagged sitewhere/service-tenant-management:2.0.ea1

> Task :service-tenant-management:dockerImage
Created image with ID 'e3f3d3baae05'.

> Task :service-user-management:dockerImage
Building image using context 'E:\Sitewhere\sitewhere\service-user-management\build\docker'.
Using tag 'docker.io/sitewhere/service-user-management:2.0.ea1' for image.

Step 1/4 : FROM openjdk:8-jre-alpine

---> b1bd879ca9b3
Step 2/4 : MAINTAINER SiteWhere "admin@sitewhere.com"

---> Using cache
---> 74ae14138418
Step 3/4 : COPY service-user-management-2.0.ea1.jar /

---> 841e35d249d3
Step 4/4 : CMD ["java", "-Xmx768m", "-jar", "/service-user-management-2.0.ea1.jar"]

---> Running in 57ed71196159
Removing intermediate container 57ed71196159
---> 8841fd97ab97
Successfully built 8841fd97ab97
Successfully tagged sitewhere/service-user-management:2.0.ea1

> Task :service-user-management:dockerImage
Created image with ID '8841fd97ab97'.

> Task :service-web-rest:npm_install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.
npm WARN extract-text-webpack-plugin@2.1.2 requires a peer of webpack@^2.2.0 but none was installed.

> Task :service-web-rest:buildUserInterface

> sitewhere@2.0.0 build E:\Sitewhere\sitewhere\sitewhere-ui
> node build/build.js

(node:1792) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

Starting to optimize CSS...
Processing static/css/app.d2ee92afff264c06c1fbfe4ad1406149.css...
Processed static/css/app.d2ee92afff264c06c1fbfe4ad1406149.css, before: 336067, after: 318289, ratio: 94.71%
[copy-webpack-plugin] WARNING - unable to locate 'E:\Sitewhere\sitewhere\sitewhere-ui\static' at 'E:\Sitewhere\sitewhere\sitewhere-ui\static'
Hash: 81555b10cfca6eb9b30aING [4m 57s]
Version: webpack 3.12.0
Time: 65657ms
                                                  Asset       Size  Chunks                    Chunk Names
                       static/img/sitewhere.a596b50.png    22.4 kB          [emitted]
                  static/js/app.5ca59a9efdc1068bf96b.js     457 kB       0  [emitted]  [big]  app
               static/js/vendor.d26307af95faa35207e8.js    2.48 MB       1  [emitted]  [big]  vendor
             static/js/manifest.5a370964cb699dabe4d6.js  873 bytes       2  [emitted]         manifest
    static/css/app.d2ee92afff264c06c1fbfe4ad1406149.css     318 kB       0  [emitted]  [big]  app
              static/js/app.5ca59a9efdc1068bf96b.js.map    2.99 MB       0  [emitted]         app
static/css/app.d2ee92afff264c06c1fbfe4ad1406149.css.map     421 kB       0  [emitted]         app
           static/js/vendor.d26307af95faa35207e8.js.map    14.2 MB       1  [emitted]         vendor
         static/js/manifest.5a370964cb699dabe4d6.js.map    9.27 kB       2  [emitted]         manifest
                                             index.html  708 bytes          [emitted]

**ERROR in [copy-webpack-plugin] unable to locate 'E:\Sitewhere\sitewhere\sitewhere-ui\static' at 'E:\Sitewhere\sitewhere\sitewhere-ui\static'**

  Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

<============-> 99% EXECUTING [5m 10s]
> :service-web-rest:dockerImage5m 9s]
>
[log.txt](https://github.com/sitewhere/sitewhere/files/2060835/log.txt)

**Comment by derekadams** [comment]
It looks like you are building the EA1 release. Can you try with the EA4 or EA5 code base? We have moved the UI application out of the main SiteWhere project, which appears to be part of the problem you are seeing.

**Comment by erliuwang** [comment]
ths
