### ISSUE TITLE
getting sitewhere-tenant.properties (No such file or directory) in log

### ISSUE THREAD

**Issue by vimalgupta** [sitewhere/sitewhere#61]
HI,

I just installed sitewhere 1.8.0 and started the server , i found in log following. 

INFO  [PropertySourcesPlaceholderConfigurer] Loading properties file from URL [file:/opt/sitewhere/conf/tenants/default/sitewhere-tenant.properties]
 WARN  [PropertySourcesPlaceholderConfigurer] Could not load properties from URL [file:/opt/sitewhere/conf/tenants/default/sitewhere-tenant.properties]: /opt/sitewhere/conf/tenants/default/sitewhere-tenant.properties (No such file or directory)

why it is throwing above?

**Comment by derekadams** [comment]
It's just a warning. There is an optional sitewhere-tenant.properties file that can be used to pass in properties for substitution. Starting with SiteWhere 1.9.0, one will be provided by default, but previous versions did not include it.
