### ISSUE TITLE
zookeeper error, opening socket connection to server 10.0.0.13/10.0.0.13:2181. Will not attempt to authenticate using SASL (unknown error)

### ISSUE THREAD

**Issue by erliuwang** [sitewhere/sitewhere#612]
Error occurs when execute "docker compose up" using file  “docker-compose.yml” in "\sitewhere-recipes-master\docker-compose\default"
it seams that the zookeeper cannot be connected.
the log file is attached below.
[docker compose up-log.txt](https://github.com/sitewhere/sitewhere/files/2064896/docker.compose.up-log.txt)

**Comment by derekadams** [comment]
Did you start the corresponding infrastructure recipe first? For instance, the infrastructure_default recipe starts all of the default services that SiteWhere depends on such as Apache Zookeeper, Apache Kafka, Mosquitto MQTT, and MongoDB. See this [section](http://sitewhere.io/docs/en/2.0.EA4/deployment/index.html#using-sitewhere-recipes-to-build-an-instance) in the EA4 documentation for more information.

**Comment by erliuwang** [comment]
of course, I start the  “docker-compose.yml” in "\sitewhere-recipes-masterr\docker-compose\infrastructure_default" first.
it seams that the infrastructure_default starts successfully.
the log file is attached below.
[docker compose up-log - infrastructure_default.txt](https://github.com/sitewhere/sitewhere/files/2065713/docker.compose.up-log.-.infrastructure_default.txt)

**Comment by derekadams** [comment]
Are you able to reproduce this error with the current EA5 branch? We have not been able to replicate the issue. For now, we will close the issue.
