### ISSUE TITLE
How long can SiteWhere 2.X use for production?

### ISSUE THREAD

**Issue by airdive** [sitewhere/sitewhere#618]
The question is as above。

**Comment by derekadams** [comment]
SiteWhere 2.x (Community Edition) may be used at no cost in production deployments as long as the application clearly displays that it is powered by SiteWhere in the user interface (and server if there are server components). There is no time limit on the usage. We will also be offering an enterprise version (SiteWhere EE) starting in the 3rd quarter of 2018. SiteWhere EE adds a number of enterprise features not available in CE and will be available under a commercial license.
