### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by fastxs** [sitewhere/sitewhere#620]
FAILURE: Build failed with an exception.

* What went wrong:
Task 'serverTar' not found in root project 'sitewhere'.

is build option no longer supported?

**Comment by derekadams** [comment]
If you are building from the *master* branch, which contains the early access code for SiteWhere 2.0, you will need to use the following documentation:

http://sitewhere.io/docs/en/2.0.EA4/development/index.html

Note that SiteWhere 2.0 is now deployed as a microservices architecture on top of Docker, so there is no single server executable any more.
