### ISSUE TITLE
how to use the streaming media module in Sitewhere2.0.rc1

### ISSUE THREAD

**Issue by erliuwang** [sitewhere/sitewhere#626]
![streaming media](https://user-images.githubusercontent.com/33246001/42368140-d4dfeb98-8138-11e8-91ca-a912568a83ed.png)
how to use the streaming media module in Sitewhere2.0.rc1？

**Comment by derekadams** [comment]
We have not completed work on the streaming media microservice. Currently the streaming media APIs from SiteWhere 1.x are still included in the device-management microservice, but there are not complete. We will be migrating them to the streaming media microservice before the final 2.0 GA release. However, these APIs are considered alpha quality and should not be used in production deployments until we finish revising them.
