### ISSUE TITLE
Migrating Event Data from MongoDB to InfluxDB

### ISSUE THREAD

**Issue by fshaikh-ces-ltd** [sitewhere/sitewhere#642]
My existing sitewhere site pushes event data to MongoDB i want to move it to InfluxDB. Is there any way i can move my existing data from Mongo To InfluxDB from sitewhere or do i need to write ETL for transfering data ?

**Comment by derekadams** [comment]
Currently, you would need to go with the ETL approach using the REST APIs or accessing the database directly to move the data from one store to another. We do plan to offer basic migration tools soon, though it will be after the 2.0 release. We also plan to have a data migration UI component which will be available as part of SiteWhere 2.0 EE later this year.

**Comment by fshaikh-ces-ltd** [comment]
Cool

**Comment by derekadams** [comment]
If you have other questions, feel free to ask on the community Discord server. The following link will add you as a member: https://discord.gg/sq7sH7B
