### ISSUE TITLE
SiteWhere 2.x - System Bootstrap and Startup

### ISSUE THREAD

**Issue by MotivDev** [sitewhere/sitewhere#654]
I am very interested in checking out version 2.0 of SiteWhere for an IoT product I am involved with.  I have been trying to deploy the system without building from the repository using the SiteWhere recipes which appear to use the prebuilt containers on docker hub from SiteWhere.  

After running the recipes I try to login to SiteWhere, it fails with incorrect login credentials.  I either am using the incorrect credentials (admin/password) or I need some type of bootstrap file to exist that builds this user for a new install.  Is this even possible from just using the pre-built containers or do I need to compile the containers myself to make this system functional?

I have read through the current 2.0.RC1 document and the section "System Bootstrap and Startup" is currently blank.  Any guidance would be much appreciated.

**Comment by derekadams** [comment]
The documentation is a work in progress right now, so thanks for your patience. Which of the recipes are you using? Generally, we recommend infrastructure_default and default, which will give you a complete system using MongoDB for persistence. If you are already doing that, are you seeing any errors in the docker-compose output when running the recipes?

**Comment by MotivDev** [comment]
Thank you for the quick response!  I have tried both the default and minimal recipes coupled with infrastructure_default recipe and still have the same error "Username does not exist"

Starting SiteWhere 'default' recipe there are multiple errors similar to the following:  

> instance-management_1  | 2018-10-02 09:31:24.095 ERROR 1 --- [croservice Main] c.s.i.templates.InstanceTemplateManager  : Microservice was null for component 'com.sitewhere.instance.templates.InstanceTemplateManager'. Unable to forward log message.

When trying to enter "admin / password" for login credentials results in the following error:

> user-management_1      | 2018-10-02 09:35:40.177 ERROR 1 --- [ault-executor-0] com.sitewhere.grpc.client.GrpcUtils      : Server exception in call to com.sitewhere.grpc.service.UserManagement/Authenticate.
user-management_1      |
user-management_1      | com.sitewhere.spi.SiteWhereSystemException: Username does not exist.
user-management_1      | 	at com.sitewhere.user.persistence.mongodb.MongoUserManagement.assertUser(MongoUserManagement.java:343) ~[classes!/:na]
user-management_1      | 	at com.sitewhere.user.persistence.mongodb.MongoUserManagement.authenticate(MongoUserManagement.java:140) ~[classes!/:na]
user-management_1      | 	at com.sitewhere.user.UserManagementDecorator.authenticate(UserManagementDecorator.java:67) ~[sitewhere-core-2.0.rc2.jar!/:na]
user-management_1      | 	at com.sitewhere.user.UserManagementDecorator.authenticate(UserManagementDecorator.java:67) ~[sitewhere-core-2.0.rc2.jar!/:na]
user-management_1      | 	at com.sitewhere.user.UserManagementDecorator.authenticate(UserManagementDecorator.java:67) ~[sitewhere-core-2.0.rc2.jar!/:na]
user-management_1      | 	at com.sitewhere.user.grpc.UserManagementImpl.authenticate(UserManagementImpl.java:135) ~[classes!/:na]
user-management_1      | 	at com.sitewhere.grpc.service.UserManagementGrpc$MethodHandlers.invoke(UserManagementGrpc.java:1468) [sitewhere-grpc-user-management-2.0.rc2.jar!/:na]
user-management_1      | 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171) [grpc-stub-1.12.0.jar!/:1.12.0]
user-management_1      | 	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) [grpc-core-1.12.0.jar!/:1.12.0]
user-management_1      | 	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) [grpc-core-1.12.0.jar!/:1.12.0]
user-management_1      | 	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) [grpc-core-1.12.0.jar!/:1.12.0]
user-management_1      | 	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) [grpc-core-1.12.0.jar!/:1.12.0]
user-management_1      | 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283) [grpc-core-1.12.0.jar!/:1.12.0]
user-management_1      | 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:706) [grpc-core-1.12.0.jar!/:1.12.0]
user-management_1      | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.12.0.jar!/:1.12.0]
user-management_1      | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.12.0.jar!/:1.12.0]
user-management_1      | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
user-management_1      | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
user-management_1      | 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
user-management_1      |
web-rest_1             | 2018-10-02 09:35:40.251 ERROR 1 --- [nio-8080-exec-1] c.s.w.s.SiteWhereAuthenticationProvider  : Authentication exception.
web-rest_1             |
web-rest_1             | com.sitewhere.spi.SiteWhereSystemException: Username does not exist.
web-rest_1             | 	at com.sitewhere.grpc.client.GrpcUtils.handleClientMethodException(GrpcUtils.java:233) ~[sitewhere-grpc-client-2.0.rc2.jar!/:na]
web-rest_1             | 	at com.sitewhere.grpc.client.user.UserManagementApiChannel.authenticate(UserManagementApiChannel.java:144) ~[sitewhere-grpc-user-management-2.0.rc2.jar!/:na]
web-rest_1             | 	at com.sitewhere.web.security.SiteWhereAuthenticationProvider.authenticateBasicAuth(SiteWhereAuthenticationProvider.java:85) [classes!/:na]
web-rest_1             | 	at com.sitewhere.web.security.SiteWhereAuthenticationProvider.authenticate(SiteWhereAuthenticationProvider.java:57) [classes!/:na]
web-rest_1             | 	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174) [spring-security-core-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
web-rest_1             | 	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:199) [spring-security-core-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
web-rest_1             | 	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$AuthenticationManagerDelegator.authenticate(WebSecurityConfigurerAdapter.java:512) [spring-security-config-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
web-rest_1             | 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:180) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
web-rest_1             | 	at com.sitewhere.web.security.basic.LimitedBasicAuthFilter.doFilterInternal(LimitedBasicAuthFilter.java:62) [classes!/:na]
web-rest_1             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
web-rest_1             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at com.sitewhere.web.security.jwt.TokenAuthenticationFilter.doFilterInternal(TokenAuthenticationFilter.java:103) [classes!/:na]
web-rest_1             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
web-rest_1             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
web-rest_1             | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) [spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
web-rest_1             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
web-rest_1             | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
web-rest_1             | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.28.jar!/:8.5.28]
web-rest_1             | 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
web-rest_1             |
web-rest_1             | 2018-10-02 09:35:40.340  INFO 1 --- [nio-8080-exec-1] c.s.web.auth.controllers.JwtService      : No credentials passsed when requesting JWT.
 
Please find attached the full log file from the 'default' recipe from start to login failure:

[SiteWhere Default Log.txt](https://github.com/sitewhere/sitewhere/files/2437402/SiteWhere.Default.Log.txt)

Thank you again for the quick response!

**Comment by derekadams** [comment]
It looks like all of the microservices started, but the part of the system that bootstraps the initial data (which includes the default users and tenant) did not run. If you can shutdown everything, delete the `data` directory which has all of the persistent data, then re-run `docker-compose up` and capture the resulting logs, I should be able to tell more about why the initial bootstrapping process is failing. Thanks!

**Comment by MotivDev** [comment]
It works!!!!  I removed the data directory and restarted infrastructure_default and default and I'm now able to log in!  Something must have happened after the initial install that resulted in the data being corrupted during first install last week. 

Thank you for the quick response and helping me get this tool up!  If I have further questions, is there a better way to contact you than here?

**Comment by derekadams** [comment]
Glad to hear that fixed the problem! If you need to ask questions or get in touch directly, join our Discord server, which includes channels for support, feature requests, etc..

https://discord.gg/sq7sH7B

**Comment by anhdenday** [comment]
Dear Derek,
I've got same problem, I've follow you to deleted data folder but it's could not solved the problem.
I am using ubuntu 18.04 LTS. Please help me to check it out.
Thanks you so much
![sitewhere](https://user-images.githubusercontent.com/6926208/47003147-c9eed580-d158-11e8-961e-fe896ac0b297.png)

**Comment by dddmw** [comment]
@anhdenday Maybe  you also need to delete the sitewhere node in zookeeper
