### ISSUE TITLE
Enhancement of the Current Logo

### ISSUE THREAD

**Issue by debpedrano** [sitewhere/sitewhere#662]
The Project already have a nice logo, but the thing is it has not properly colored and need a little bit of enhancement. Can I make some beautification on it?

**Comment by debpedrano** [comment]
I included Fav Icon Logo and its Logo Mark

![image](https://user-images.githubusercontent.com/40510200/47288716-d75d0180-d629-11e8-8da3-f0e25c6d4b25.png)

**Comment by debpedrano** [comment]
It may look the same to the old/current one, but on this proposal I will include fav icons, logo mark and logo type with svg.

**Comment by debpedrano** [comment]
@derekadams
 It may look the same to the old/current one, but on this proposal I will include fav icons, logo mark and logo type with svg.

**Comment by derekadams** [comment]
Sorry, but the feedback has indicated that people prefer the original style. The logo and color palette were chosen from a lot of other proposals, so I think we are going to stay with what we have. Thanks for your effort though!
