### ISSUE TITLE
Sending Json device registration request from external application

### ISSUE THREAD

**Issue by iotinformant** [sitewhere/sitewhere#68]
Dear members,
I am running an instance of the sitewhere server. I want to register a device by sending Json query by external application in .NET. Following is my code : 

 var httpWebRequest = (HttpWebRequest)WebRequest.Create("http://localhost:8080/sitewhere");
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.Method = "POST";
            string username = "admin";
            string password = "password";
            String encoded = System.Convert.ToBase64String(System.Text.Encoding.GetEncoding("ISO-8859-1").GetBytes(username + ":" + password));

         
            using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
            {
                string json = "{\"createdDate\":\"2016-10-04T09:36:19.340+0530\"," +
                              "\"createdBy\":\"admin\"," +
                              "\"deleted\":\"false\"," +
                              "\"hardwareId\":\"00067\"," +
                              "\"siteToken\":\"bb105f8d-3150-41f5-b9d1-db04965668d3\"," +
                              "\"deviceElementMappings\":\"[]\"," +
                              "\"comments\":\"Tool Tracker. Device generated by model initializer.\","+
                              "\"specification\":\"{\"createdDate\":\"2016-08-24T13:45:26.267+0530\"," +
                              "\"createdBy\":\"system\"," +
                              "\"deleted\":\"false\"," +
                              "\"token\":\"964e7613-dab3-4fb3-8919-266a91370884\"," +
                              "\"name\":\"Node-RED\"," +
                              "\"assetModuleId\":\"fs-devices\"," +
                              "\"assetId\":\"195\"," +
                              "\"assetName\":\"Node-RED Virtual Device\"," +
                              "\"assetImageUrl\":\"https://s3.amazonaws.com/sitewhere-demo/gateway/node-red.png\"," +
                              "\"containerPolicy\":\"Standalone\"," +
                              "\"metadata\":\"{}\"}\"," +
                              "\"metadata\":\"{}\" }";

                streamWriter.Write(json);
                streamWriter.Flush();
                streamWriter.Close();

            }
            try
            {
                var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
                using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
                {
                    var result = streamReader.ReadToEnd();
                }
            }
            catch (System.Exception excep)
            {

                MessageBox.Show(excep.Message);

            }

I am sending the request wrong or is there a problem with the URI to which i am sending the request ? Thanks in advance.

**Comment by iotinformant** [comment]
@derekadams

**Comment by derekadams** [comment]
It appears that you are sending data in the wrong format. For the correct format, see:

http://documentation.sitewhere.org/rest/single.html#createDevice

**Comment by iotinformant** [comment]
@derekadams  here is my updated code 


using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Sitewhere_connect
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            HttpWebRequest req = (HttpWebRequest)WebRequest.Create(@"http://localhost:1883/SiteWhere/input/json");
            req.Method = "POST";
            // Create Client
            WebClient client = new WebClient();
            // Assign Credentials
            client.Credentials = new NetworkCredential("admin", "password", "sitewhere1234567890");
            req.Credentials = CredentialCache.DefaultCredentials;
            using (var streamWriter = new StreamWriter(req.GetRequestStream()))
            {
                string json = "{\"hardwareId\":\"123456789\"," +
                              "\"siteToken\":\"bb105f8d-3150-41f5-b9d1-db04965668d3\"," +
                              "\"specificationToken\":\"82043707-9e3d-441f-bdcc-33cf0f4f7260\"," +
                              "\"comments\":\"Equipment tracker.\" }";
                streamWriter.Write(json);
                streamWriter.Flush();
                streamWriter.Close();

            }
            try
            {
                var httpResponse = (HttpWebResponse)req.GetResponse();
                using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
                {
                    var result = streamReader.ReadToEnd();
                }
            }
            catch (System.Exception excep)
            {
                MessageBox.Show(excep.Message);

            }

        }
    }

}


            Still unable to register device to sitewhere via external applications

**Comment by iotinformant** [comment]
![error](https://cloud.githubusercontent.com/assets/22866212/19465339/03a7bc18-9521-11e6-8478-68cb98c120c1.jpg)

**Comment by derekadams** [comment]
The JSON payload looks correct, so the problem is probably with authentication. I am not a .Net developer, but the credentials require two HTTP headers to be sent -- the authentication header and the tenant token header. An explanation of the headers is provided here:

http://documentation.sitewhere.org/rest/single.html#calling

Also, it was mentioned on the Google group that a C#/.Net library is under development, so that may be an option soon as well:

https://groups.google.com/forum/#!searchin/sitewhere/.Net%7Csort:relevance/sitewhere/drMiBdsUVYI/lazRKt_yBQAJ

**Comment by iotinformant** [comment]
@derekadams  thanks for your reply... As you mentioned the problem was with authentication itself. I am able to solve that. Now i am able to register device to sitewhere via .net application. Thanks again

**Comment by Abel-Liu** [comment]
@iotinformant  Hi, I am trying to connect to SiteWhere server using C#,  can you help me how to do that?
Thx
