### ISSUE TITLE
Command Invocations doesn't work to invoke ~

### ISSUE THREAD

**Issue by GanKanTechnology** [sitewhere/sitewhere#682]
As the title says,  sitewhere-2.0.1 images deployed with docker-compose on a standalone server.   
steps as follows:
Device Management----Devices----choose a device----COMMAND INVOCATIONS----Invoke Command
then got nothing. We use a desktop  tool to play the subscriber role.
The mosquitto service itself  can work, if we use the desktop tool to play both the  publisher role and the subscriber role , the subscriber could get messages that has been published.

**Comment by GanKanTechnology** [comment]
They solved it and we are carrying on to do more tests~

**Comment by x-falcon** [comment]
@GanKanTechnology how solved it ?

**Comment by x-falcon** [comment]
@GanKanTechnology hello, can share the method?

**Comment by derekadams** [comment]
Hi @x-falcon The method you need to invoke to fire the command is: https://sitewhere.io/docs/2.0.0/api2/#operation/createCommandInvocationUsingPOST

The transport on which the command is delivered depends on how the command delivery microservice is configured for that tenant. The default is to deliver commands using MQTT on the topic `SiteWhere/${tenant}/command/${device}` where `$tenant` is the tenant token and `$device` is the device token.
