### ISSUE TITLE
How to put a trigger script if we want to send a http request under specified conditions？

### ISSUE THREAD

**Issue by GanKanTechnology** [sitewhere/sitewhere#685]
Hi guys~

We're testing sitewhere 2.0.1 platform with some hardware devices. Now we have an actural need : we want to identify the content which is sent to the mosquitto-svc  by the hardware device, and if we got the designated string, then a http quest  will  be sent to a designated IP address. 

In the past, we did this by a trigger in the mysql database. The designated  string was distinguished by  java code and was inserted into a specific table in mysql. Then the trigger on that table send a http request to http://xxx.xxx.xx/xxx. Since the method of triggers in database was inefficient and now sitewhere uses mongodb which seems don't support trigger, we have to find a new way to do this. 

On the sitewhere-admin-ui, we found somewhere to create scripts.  It located at  "Manage Tenant Microservice: Event Sources -->MQTT Event Source (json)-->Open-->Scripts-->+ Create".  
From here we could see a script template named "Binary Event Decoder" and we think we could add our scripts  here too. But there're still some questions:

Question 1: Is it  really the right place where we should edit our own trigger script ?
Qusetion 2: What pattern should we use ? The script template seems written with Groovy not Java. 
Qusetion 3: How do we get the content that sent by the devices? Which functions or libs should we call or import ?
Hmmm.........Maybe that's too many questions, would you please spare your time to  give me a simple demo scripts about that, please? Thanks a lot for your work !

**Comment by derekadams** [comment]
Hi @GanKanTechnology, you are correct regarding the approach of plugging a script into the event pipeline. We will put together an example of sending an HTTP request in response to an event.

**Comment by derekadams** [comment]
We are working on a standardized solution for this use case based on the outbound connectors microservice. See #686.

**Comment by derekadams** [comment]
This functionality has been added in the `sitewhere-2.0.3` release. We will add documentation as soon as possible.
