### ISSUE TITLE
On Installation of K8s Cluster

### ISSUE THREAD

**Issue by gejiwei** [sitewhere/sitewhere#687]
![_20190124111829](https://user-images.githubusercontent.com/39801390/51652211-cf668200-1fc9-11e9-8c34-639076afddbd.png)
Install SiteWhere from SiteWhere Repository，Other installations can't be found. / Sitewhere, pod can't get up now. What's the reason?

**Comment by derekadams** [comment]
Can you provide more information to help us diagnose the issue? We have a bug template that includes questions about environment and other factors that would affect system startup.

**Comment by gejiwei** [comment]
My helm version
![image](https://user-images.githubusercontent.com/39801390/51659128-a1426b80-1fe4-11e9-9ee3-2c09bfd380a9.png)

**Comment by gejiwei** [comment]
**Operate these three steps**

helm repo add sitewhere https://sitewhere.io/helm-charts
helm repo update
helm install --name sitewhere sitewhere/sitewhere

**Comment by gejiwei** [comment]
![image](https://user-images.githubusercontent.com/39801390/51669018-7f55e280-1ffe-11e9-9b60-89ac4bfdab7e.png)
![image](https://user-images.githubusercontent.com/39801390/51669041-91d01c00-1ffe-11e9-990e-f0de3e87c828.png)
Do Rook persistent volumes need to be created manually? How to operate? Is this related to the inability of sitewhere to start? Solution? Thank you

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @gejiwei, there seems to be a problem with Rook.

Can you verify that the `rook-ceph-agent` pods are `Running`

```console
kubectl -n rook-ceph-system get pod
```

Also, verify that there are not error on `rook-ceph-agent` pods by running:

```console
kubectl -n rook-ceph-system get pod -l app=rook-ceph-agent -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.status.containerStatuses[0].lastState.terminated.message}{"\n"}{end}'
```
Take a look a [this](https://rook.io/docs/rook/v0.9/common-issues.html) document for common issues with Rook.  
Your pod are `Pending` (`Reason: CrashLoopBackOff`) because MongoDB, Kafka and Apache Zookeeper can not get Bound to PVC.

**Comment by gejiwei** [comment]
hello， @Jorge  Eduardo Villaverde， Thank you very much for answering my question, but why did it happen? I just took three steps.

kubectl create -f rook/operator.yaml
kubectl create -f rook/cluster.yaml
kubectl create -f rook/storageclass.yaml

![image](https://user-images.githubusercontent.com/39801390/51718733-a43f6980-2081-11e9-853e-04757690794a.png)

**Comment by jorgevillaverde-sitewhere** [comment]
I'm not sure, take a look at this [issue](https://github.com/rook/rook/issues/2289), it may help you.

**Comment by gejiwei** [comment]
If I don't deploy rook, can I install sitewhere directly and where to download the installed directory?
![image](https://user-images.githubusercontent.com/39801390/51735401-5008a980-20c2-11e9-8863-c67e17fcdfc9.png)

**Comment by jorgevillaverde-sitewhere** [comment]
Yes, you can deploy SiteWhere without using Rook.io.

Assuming that you had a storageClass names `hostpath` on your system, you can install SiteWhere using: 

```console
helm install --name sitewhere \
--set sitewhere-infra-database.mongodb.persistence.storageClass=hostpath \
--set sitewhere-infra-core.kafka.persistence.storageClass=hostpath \
--set sitewhere-infra-core.kafka.zookeeper.persistence.storageClass=hostpath \
sitewhere/sitewhere
```
The installed directory would depend on the `storageClass` you use.

**Comment by gejiwei** [comment]
The problem with installing me was rook. I redeployed the k8s cluster. I did the following steps to install it. But this error is a namespace problem. How can I solve it? Thank you very much.

![image](https://user-images.githubusercontent.com/39801390/51956067-2dd7a880-2481-11e9-8cba-d1b275880bb8.png)


helm repo add sitewhere https://sitewhere.io/helm-charts
helm repo update
helm install --name sitewhere sitewhere/sitewhere

[root@k8s-master charts]# helm install --name sitewhere sitewhere/sitewhere
Error: release sitewhere failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "default"

**Comment by gejiwei** [comment]
I've solved the problem above, but there are new problems after installation. This time it's not rook's problem.The same problem with installation

![image](https://user-images.githubusercontent.com/39801390/51966501-a6e9f680-24a7-11e9-9ade-117f6cf2f34a.png)
![image](https://user-images.githubusercontent.com/39801390/51966534-be28e400-24a7-11e9-8d3c-3616d2e31f4d.png)

**Comment by gejiwei** [comment]
[root@k8s-master charts]# kubectl describe pvc data-sitewhere-zookeeper-0 
Name:          data-sitewhere-zookeeper-0
Namespace:     default
StorageClass:  rook-ceph-block
Status:        Pending
Volume:        
Labels:        app=zookeeper
               component=server
               release=sitewhere
Annotations:   control-plane.alpha.kubernetes.io/leader:
                 {"holderIdentity":"57124cfd-243a-11e9-a99e-0242ac110604","leaseDurationSeconds":15,"acquireTime":"2019-01-30T07:42:39Z","renewTime":"2019-...
               volume.beta.kubernetes.io/storage-provisioner: ceph.rook.io/block
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
Events:
  Type     Reason                Age                 From                                                                                         Message
  ----     ------                ----                ----                                                                                         -------
  Normal   ExternalProvisioning  22m (x82 over 27m)  persistentvolume-controller                                                                  waiting for a volume to be created, either by external provisioner "ceph.rook.io/block" or manually created by system administrator
  Normal   ExternalProvisioning  19m (x6 over 20m)   persistentvolume-controller                                                                  waiting for a volume to be created, either by external provisioner "ceph.rook.io/block" or manually created by system administrator
  Warning  ProvisioningFailed    15m (x13 over 27m)  ceph.rook.io/block rook-ceph-operator-67f585458f-whv9d 57124cfd-243a-11e9-a99e-0242ac110604  Failed to provision volume with StorageClass "rook-ceph-block": Failed to create rook block image replicapool/pvc-9e89cfb6-2462-11e9-aae1-02002dfd002c: failed to create image pvc-9e89cfb6-2462-11e9-aae1-02002dfd002c in pool replicapool of size 5368709120: Failed to complete '': exit status 2. rbd: error opening pool 'replicapool': (2) No such file or directory
. output:
  Normal     Provisioning          10m (x15 over 27m)     ceph.rook.io/block rook-ceph-operator-67f585458f-whv9d 57124cfd-243a-11e9-a99e-0242ac110604  External provisioner is provisioning volume for claim "default/data-sitewhere-zookeeper-0"
  Normal     ExternalProvisioning  4m17s (x199 over 19m)  persistentvolume-controller                                                                  waiting for a volume to be created, either by external provisioner "ceph.rook.io/block" or manually created by system administrator
Mounted By:  <none>
[root@k8s-master charts]# kubectl describe pvc data-sitewhere-zookeeper-0 
Name:          data-sitewhere-zookeeper-0
Namespace:     default
StorageClass:  rook-ceph-block
Status:        Pending
Volume:        
Labels:        app=zookeeper
               component=server
               release=sitewhere
Annotations:   control-plane.alpha.kubernetes.io/leader:
                 {"holderIdentity":"57124cfd-243a-11e9-a99e-0242ac110604","leaseDurationSeconds":15,"acquireTime":"2019-01-30T07:42:39Z","renewTime":"2019-...
               volume.beta.kubernetes.io/storage-provisioner: ceph.rook.io/block
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
Events:
  Type     Reason                Age                 From                                                                                         Message
  ----     ------                ----                ----                                                                                         -------
  Normal   ExternalProvisioning  22m (x82 over 27m)  persistentvolume-controller                                                                  waiting for a volume to be created, either by external provisioner "ceph.rook.io/block" or manually created by system administrator
  Normal   ExternalProvisioning  20m (x6 over 20m)   persistentvolume-controller                                                                  waiting for a volume to be created, either by external provisioner "ceph.rook.io/block" or manually created by system administrator
  Warning  ProvisioningFailed    15m (x13 over 27m)  ceph.rook.io/block rook-ceph-operator-67f585458f-whv9d 57124cfd-243a-11e9-a99e-0242ac110604  Failed to provision volume with StorageClass "rook-ceph-block": Failed to create rook block image replicapool/pvc-9e89cfb6-2462-11e9-aae1-02002dfd002c: failed to create image pvc-9e89cfb6-2462-11e9-aae1-02002dfd002c in pool replicapool of size 5368709120: Failed to complete '': exit status 2. rbd: error opening pool 'replicapool': (2) No such file or directory
. output:
  Normal     Provisioning          10m (x15 over 27m)     ceph.rook.io/block rook-ceph-operator-67f585458f-whv9d 57124cfd-243a-11e9-a99e-0242ac110604  External provisioner is provisioning volume for claim "default/data-sitewhere-zookeeper-0"
  Normal     ExternalProvisioning  4m38s (x199 over 19m)  persistentvolume-controller                                                                  waiting for a volume to be created, either by external provisioner "ceph.rook.io/block" or manually created by system administrator
Mounted By:  <none>

**Comment by gejiwei** [comment]
[root@k8s-master charts]# helm install --name sitewhere sitewhere/sitewhere
NAME:   sitewhere
LAST DEPLOYED: Wed Jan 30 15:42:34 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1beta2/Deployment
NAME                           DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
sitewhere-asset-management     1        1        1           0          4s
sitewhere-batch-operations     1        1        1           0          4s
sitewhere-command-delivery     1        1        1           0          4s
sitewhere-device-management    1        1        1           0          4s
sitewhere-device-registration  1        1        1           0          4s
sitewhere-device-state         1        0        0           0          4s
sitewhere-event-management     1        1        1           0          4s
sitewhere-event-search         1        1        1           0          3s
sitewhere-event-sources        1        0        0           0          3s
sitewhere-inbound-processing   1        0        0           0          3s
sitewhere-instance-management  1        0        0           0          3s
sitewhere-jaeger               1        0        0           0          3s
sitewhere-label-generation     1        0        0           0          3s
sitewhere-mosquitto            1        0        0           0          3s
sitewhere-outbound-connectors  1        0        0           0          3s
sitewhere-rule-processing      1        0        0           0          3s
sitewhere-schedule-management  1        0        0           0          3s
sitewhere-streaming-media      1        0        0           0          3s
sitewhere-tenant-management    1        0        0           0          3s
sitewhere-user-management      1        0        0           0          3s
sitewhere-web-rest             1        0        0           0          3s

==> v1beta1/StatefulSet
NAME                 DESIRED  CURRENT  AGE
sitewhere-consul     3        0        3s
sitewhere-zookeeper  3        0        3s
sitewhere-kafka      3        1        3s

==> v1/StatefulSet
NAME                         DESIRED  CURRENT  AGE
sitewhere-mongodb-arbiter    1        0        3s
sitewhere-mongodb-primary    1        0        3s
sitewhere-mongodb-secondary  1        0        3s

==> v1/Pod(related)
NAME                                            READY  STATUS             RESTARTS  AGE
sitewhere-asset-management-64b75cb746-lls8n     0/1    ContainerCreating  0         4s
sitewhere-batch-operations-c67c5f946-vs6c6      0/1    ContainerCreating  0         4s
sitewhere-command-delivery-56f6d844f4-s8szl     0/1    ContainerCreating  0         4s
sitewhere-device-management-85d76df5fb-rs49n    0/1    ContainerCreating  0         4s
sitewhere-device-registration-57d4588f44-w9sb7  0/1    ContainerCreating  0         3s
sitewhere-device-state-77798ff786-qgp7k         0/1    ContainerCreating  0         3s
sitewhere-event-management-6895484b94-tpfrg     0/1    ContainerCreating  0         3s
sitewhere-event-search-7779fb8bc8-snh22         0/1    ContainerCreating  0         3s
sitewhere-event-sources-979d59d5b-zbn5f         0/1    ContainerCreating  0         3s
sitewhere-inbound-processing-55569bfc66-7bml5   0/1    Pending            0         3s
sitewhere-instance-management-6745c45464-qf2nr  0/1    Pending            0         3s
sitewhere-jaeger-66c9b6769b-d9r9b               0/1    ContainerCreating  0         2s
sitewhere-label-generation-7c96d6b8b-kmc5l      0/1    Pending            0         2s
sitewhere-mosquitto-6db6959798-zslql            0/1    ContainerCreating  0         2s
sitewhere-outbound-connectors-7954754588-chc8t  0/1    Pending            0         2s
sitewhere-rule-processing-84dbfc4c84-n854x      0/1    Pending            0         1s
sitewhere-kafka-0                               0/1    Pending            0         3s

==> v1beta1/PodDisruptionBudget
NAME                         MIN AVAILABLE  MAX UNAVAILABLE  ALLOWED DISRUPTIONS  AGE
sitewhere-consul-pdb         N/A            1                0                    5s
sitewhere-zookeeper          N/A            1                0                    5s
sitewhere-mongodb-arbiter    1              N/A              0                    5s
sitewhere-mongodb-primary    1              N/A              0                    5s
sitewhere-mongodb-secondary  1              N/A              0                    5s

==> v1/Secret
NAME                         TYPE    DATA  AGE
sitewhere-consul-gossip-key  Opaque  1     5s

==> v1/ConfigMap
NAME                    DATA  AGE
sitewhere-consul-tests  1     5s

==> v1/Service
NAME                               TYPE          CLUSTER-IP  EXTERNAL-IP  PORT(S)                                                                           AGE
sitewhere-consul                   ClusterIP     None        <none>       8500/TCP,8400/TCP,8301/TCP,8301/UDP,8302/TCP,8302/UDP,8300/TCP,8600/TCP,8600/UDP  5s
sitewhere-consul-ui                NodePort      10.0.0.145  <none>       8500:35609/TCP                                                                    5s
sitewhere-zookeeper-headless       ClusterIP     None        <none>       2181/TCP,3888/TCP,2888/TCP                                                        5s
sitewhere-zookeeper                NodePort      10.0.0.36   <none>       2181:35379/TCP                                                                    5s
sitewhere-0-external               NodePort      10.0.0.121  <none>       19092:31090/TCP                                                                   5s
sitewhere-2-external               NodePort      10.0.0.191  <none>       19092:31092/TCP                                                                   5s
sitewhere-1-external               NodePort      10.0.0.159  <none>       19092:31091/TCP                                                                   5s
sitewhere-kafka                    ClusterIP     10.0.0.120  <none>       9092/TCP                                                                          5s
sitewhere-kafka-headless           ClusterIP     None        <none>       9092/TCP                                                                          5s
sitewhere-mongodb-headless         ClusterIP     None        <none>       27017/TCP                                                                         5s
sitewhere-mongodb                  ClusterIP     10.0.0.96   <none>       27017/TCP                                                                         5s
sitewhere-asset-management-svc     ClusterIP     None        <none>       9000/TCP,9001/TCP                                                                 5s
sitewhere-batch-operations-svc     ClusterIP     None        <none>       9000/TCP,9001/TCP                                                                 5s
sitewhere-command-delivery-svc     ClusterIP     10.0.0.134  <none>       9000/TCP,9001/TCP                                                                 5s
sitewhere-device-management-svc    ClusterIP     None        <none>       9000/TCP,9001/TCP                                                                 5s
sitewhere-device-registration-svc  ClusterIP     10.0.0.122  <none>       9000/TCP,9001/TCP                                                                 4s
sitewhere-device-state-svc         ClusterIP     10.0.0.230  <none>       9000/TCP,9001/TCP                                                                 4s
sitewhere-event-management-svc     ClusterIP     None        <none>       9000/TCP,9001/TCP                                                                 4s
sitewhere-event-search-svc         ClusterIP     10.0.0.158  <none>       9000/TCP,9001/TCP                                                                 4s
sitewhere-event-sources-svc        ClusterIP     10.0.0.119  <none>       9000/TCP,9001/TCP                                                                 4s
sitewhere-inbound-processing-svc   ClusterIP     10.0.0.13   <none>       9000/TCP,9001/TCP                                                                 4s
sitewhere-instance-management-svc  ClusterIP     10.0.0.83   <none>       9000/TCP,9001/TCP                                                                 4s
sitewhere-jaeger-svc               ClusterIP     10.0.0.28   <none>       9411/TCP,16686/TCP                                                                4s
sitewhere-label-generation-svc     ClusterIP     10.0.0.218  <none>       9000/TCP,9001/TCP                                                                 4s
sitewhere-mosquitto-svc            LoadBalancer  10.0.0.105  <pending>    1883:39655/TCP                                                                    4s
sitewhere-outbound-connectors-svc  ClusterIP     10.0.0.17   <none>       9000/TCP,9001/TCP                                                                 4s
sitewhere-rule-processing-svc      ClusterIP     10.0.0.49   <none>       9000/TCP,9001/TCP                                                                 4s
sitewhere-schedule-management-svc  ClusterIP     None        <none>       9000/TCP,9001/TCP                                                                 4s
sitewhere-streaming-media-svc      ClusterIP     10.0.0.10   <none>       9000/TCP,9001/TCP                                                                 4s
sitewhere-tenant-management-svc    ClusterIP     None        <none>       9000/TCP,9001/TCP                                                                 4s
sitewhere-user-management-svc      ClusterIP     None        <none>       9000/TCP,9001/TCP                                                                 4s
sitewhere-web-rest-http            LoadBalancer  10.0.0.47   <pending>    8080:47864/TCP                                                                    4s
sitewhere-web-rest-grpc            ClusterIP     10.0.0.101  <none>       9000/TCP,9001/TCP                                                                 4s


NOTES:
1. Get SiteWhere application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get svc -w sitewhere-web-rest-http'
  export SERVICE_IP=$(kubectl get svc --namespace default sitewhere-web-rest-http -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
  echo http://$SERVICE_IP:8080
  To login to SiteWhere Admin Console use:
  - Username: admin
  - Password: password
  - Protocol: http
  - Server: $SERVICE_IP
  - Port: 8080

**Comment by jorgevillaverde-sitewhere** [comment]
> I've solved the problem above, but there are new problems after installation. This time it's not rook's problem.The same problem with installation
> 
> ![image](https://user-images.githubusercontent.com/39801390/51966501-a6e9f680-24a7-11e9-9ade-117f6cf2f34a.png)
> ![image](https://user-images.githubusercontent.com/39801390/51966534-be28e400-24a7-11e9-8d3c-3616d2e31f4d.png)

Your PVC are `Pending`, you don't need to create them manually, that's Rook job. From what I see Rook.io is not working.

**Comment by jorgevillaverde-sitewhere** [comment]
Please follow these [common issues](https://rook.io/docs/rook/v0.9/common-issues.html).

**Comment by gejiwei** [comment]
I found some mistakes.
 failed to create cluster in namespace rook-ceph. failed to start the osds. 2 failures encountered while running osds in namespace rook-ceph: timed out waiting for 2 nodes: &{values:map[192.168.2.245:{} 192.168.2.8:{}]}

**Comment by derekadams** [comment]
This definitely looks like a problem in the underlying Ceph storage that Rook uses. We are currently investigating using [EdgeFS](https://rook.io/docs/rook/v0.9/edgefs-storage.html) as an alternative to see if it works better. In the meantime, the link that @jorgevillaverde-sitewhere provided covers the common issues with Ceph in various environments.

**Comment by gejiwei** [comment]
Thank you very much. Happy New Year.

**Comment by derekadams** [comment]
I'm going to close this for now. We upgraded to Rook 1.0, which probably addresses these issues. If not, it should be reported as a Rook bug.
