### ISSUE TITLE
New Installation Problems

### ISSUE THREAD

**Issue by gejiwei** [sitewhere/sitewhere#690]
The problem with installing me was rook. I redeployed the k8s cluster. I did the following steps to install it. But this error is a namespace problem. How can I solve it? Thank you very much.

![image](https://user-images.githubusercontent.com/39801390/51955627-73937180-247f-11e9-87eb-6dd35b3034e0.png)

helm repo add sitewhere https://sitewhere.io/helm-charts
helm repo update
helm install --name sitewhere sitewhere/sitewhere

[root@k8s-master charts]# helm install --name sitewhere sitewhere/sitewhere
Error: release sitewhere failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "default"

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @gejiwei, how did you solve the problem?

Did you use the following command?
```console
kubectl create clusterrolebinding permissive-binding --clusterrole=cluster-admin --user=admin --user=kubelet --group=system:serviceaccounts;
```
