### ISSUE TITLE
Groovy outbound connector filter: Add device and other context info for event

### ISSUE THREAD

**Issue by derekadams** [sitewhere/sitewhere#696]
The variables passed to the binding for the current implementation of the Groovy filter for outbound connectors does not contain enough information to do effective filtering. Add the device, assignment, and other context information that gives the user more power over filtering.

**Comment by tidehc** [comment]
Hi,Has the current version 2.0.6 solved this issue?

**Comment by derekadams** [comment]
It's not added yet, but will be before 2.0.6 is officially released. We have been sidetracked with updates to other non-core parts of the system for the past few weeks. We'll get it done soon though!

**Comment by derekadams** [comment]
This update adds access to the device, assignment and tenant for extra context within the filter script.

![image](https://user-images.githubusercontent.com/338921/55573437-f4692680-56d7-11e9-8ca5-2d11feb2f956.png)
