### ISSUE TITLE
the pods of sitewhere 2.0 don't work including "sitewhere-kafka-0","sitewhere-mongodb-secondary-0"

### ISSUE THREAD

**Issue by alanliu95** [sitewhere/sitewhere#698]
I have a k8s cluster of two nodes. After I run the command `helm install --name sitewhere sitewhere/sitewhere` and wait for long time. There are still 4 pods unavailable. There are 

1. sitewhere-kafka-0
2. sitewhere-zookeeper-1
3. sitewhere-mongodb-secondary-0
4. sitewhere-consul-0

the info from "kubectl describe" are the following:
### **liusong@ubuntu18-4th:~$ k describe pods/sitewhere-zookeeper-1**
Name:               sitewhere-zookeeper-1
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app=zookeeper
                    component=server
                    controller-revision-hash=sitewhere-zookeeper-7f864999d5
                    release=sitewhere
                    statefulset.kubernetes.io/pod-name=sitewhere-zookeeper-1
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      StatefulSet/sitewhere-zookeeper
Containers:
  zookeeper:
    Image:       gcr.io/google_samples/k8szk:v3
    Ports:       2181/TCP, 3888/TCP, 2888/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/bash
      -xec
      zkGenConfig.sh && exec zkServer.sh start-foreground
    Liveness:   exec [zkOk.sh] delay=20s timeout=1s period=10s #success=1 #failure=3
    Readiness:  exec [zkOk.sh] delay=20s timeout=1s period=10s #success=1 #failure=3
    Environment:
      ZK_REPLICAS:             3
      JMXAUTH:                 false
      JMXDISABLE:              false
      JMXPORT:                 1099
      JMXSSL:                  false
      ZK_CLIENT_PORT:          2181
      ZK_ELECTION_PORT:        3888
      ZK_HEAP_SIZE:            1G
      ZK_INIT_LIMIT:           5
      ZK_LOG_LEVEL:            INFO
      ZK_MAX_CLIENT_CNXNS:     60
      ZK_MAX_SESSION_TIMEOUT:  40000
      ZK_MIN_SESSION_TIMEOUT:  4000
      ZK_PURGE_INTERVAL:       0
      ZK_SERVER_PORT:          2888
      ZK_SNAP_RETAIN_COUNT:    3
      ZK_SYNC_LIMIT:           10
      ZK_TICK_TIME:            2000
    Mounts:
      /var/lib/zookeeper from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2tmxh (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-sitewhere-zookeeper-1
    ReadOnly:   false
  default-token-2tmxh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2tmxh
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
liusong@ubuntu18-4th:~$ 
liusong@ubuntu18-4th:~$ k describe pods/sitewhere-zookeeper-1
Name:               sitewhere-zookeeper-1
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app=zookeeper
                    component=server
                    controller-revision-hash=sitewhere-zookeeper-7f864999d5
                    release=sitewhere
                    statefulset.kubernetes.io/pod-name=sitewhere-zookeeper-1
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      StatefulSet/sitewhere-zookeeper
Containers:
  zookeeper:
    Image:       gcr.io/google_samples/k8szk:v3
    Ports:       2181/TCP, 3888/TCP, 2888/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/bash
      -xec
      zkGenConfig.sh && exec zkServer.sh start-foreground
    Liveness:   exec [zkOk.sh] delay=20s timeout=1s period=10s #success=1 #failure=3
    Readiness:  exec [zkOk.sh] delay=20s timeout=1s period=10s #success=1 #failure=3
    Environment:
      ZK_REPLICAS:             3
      JMXAUTH:                 false
      JMXDISABLE:              false
      JMXPORT:                 1099
      JMXSSL:                  false
      ZK_CLIENT_PORT:          2181
      ZK_ELECTION_PORT:        3888
      ZK_HEAP_SIZE:            1G
      ZK_INIT_LIMIT:           5
      ZK_LOG_LEVEL:            INFO
      ZK_MAX_CLIENT_CNXNS:     60
      ZK_MAX_SESSION_TIMEOUT:  40000
      ZK_MIN_SESSION_TIMEOUT:  4000
      ZK_PURGE_INTERVAL:       0
      ZK_SERVER_PORT:          2888
      ZK_SNAP_RETAIN_COUNT:    3
      ZK_SYNC_LIMIT:           10
      ZK_TICK_TIME:            2000
    Mounts:
      /var/lib/zookeeper from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2tmxh (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-sitewhere-zookeeper-1
    ReadOnly:   false
  default-token-2tmxh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2tmxh
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

### **liusong@ubuntu18-4th:~$ k describe pods/sitewhere-kafka-0**
Name:               sitewhere-kafka-0
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               vm-ubuntu/192.168.1.13
Start Time:         Wed, 06 Mar 2019 04:43:54 +0000
Labels:             app=kafka
                    controller-revision-hash=sitewhere-kafka-7cf5c774c5
                    release=sitewhere
                    statefulset.kubernetes.io/pod-name=sitewhere-kafka-0
Annotations:        <none>
Status:             Running
IP:                 10.244.2.104
Controlled By:      StatefulSet/sitewhere-kafka
Containers:
  kafka-broker:
    Container ID:  docker://0482ae3d8e0487b35f98f5d60d1159183cebfa8607068bc9952996d56bc6d20f
    Image:         confluentinc/cp-kafka:5.0.1
    Image ID:      docker-pullable://confluentinc/cp-kafka@sha256:c87b1c07fb53b1a82d24b436e53485917876a963dc67311800109fa12fe9a63d
    Port:          9092/TCP
    Host Port:     0/TCP
    Command:
      sh
      -exc
      unset KAFKA_PORT && \
      export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
      export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092 && \
      exec /etc/confluent/docker/run
      
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 07 Mar 2019 01:59:02 +0000
      Finished:     Thu, 07 Mar 2019 01:59:49 +0000
    Ready:          False
    Restart Count:  367
    Liveness:       exec [sh -ec /usr/bin/jps | /bin/grep -q SupportedKafka] delay=30s timeout=5s period=10s #success=1 #failure=3
    Readiness:      tcp-socket :kafka delay=30s timeout=5s period=10s #success=1 #failure=3
    Environment:
      POD_IP:                                          (v1:status.podIP)
      KAFKA_HEAP_OPTS:                                -Xmx1G -Xms1G
      KAFKA_ZOOKEEPER_CONNECT:                        sitewhere-zookeeper:2181
      KAFKA_LOG_DIRS:                                 /opt/kafka/data/logs
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE:         false
      KAFKA_DEFAULT_REPLICATION_FACTOR:               3
      KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS:  30
      KAFKA_MIN_INSYNC_REPLICAS:                      2
      KAFKA_NUM_PARTITIONS:                           3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:         3
      KAFKA_JMX_PORT:                                 5555
    Mounts:
      /opt/kafka/data from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2tmxh (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir-sitewhere-kafka-0
    ReadOnly:   false
  default-token-2tmxh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2tmxh
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                     From                Message
  ----     ------     ----                    ----                -------
  Warning  Unhealthy  23m (x503 over 21h)     kubelet, vm-ubuntu  Liveness probe failed:
  Warning  BackOff    8m47s (x4651 over 21h)  kubelet, vm-ubuntu  Back-off restarting failed container
  Warning  Unhealthy  3m28s (x621 over 21h)   kubelet, vm-ubuntu  Readiness probe failed: dial tcp 10.244.2.104:9092: connect: connection refused
liusong@ubuntu18-4th:~$ 

### **liusong@ubuntu18-4th:~$ k describe pods/sitewhere-mongodb-secondary-0**
Name:               sitewhere-mongodb-secondary-0
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               vm-ubuntu/192.168.1.13
Start Time:         Wed, 06 Mar 2019 04:43:55 +0000
Labels:             app=mongodb
                    chart=mongodb-5.2.0
                    component=secondary
                    controller-revision-hash=sitewhere-mongodb-secondary-8559c546d4
                    release=sitewhere
                    statefulset.kubernetes.io/pod-name=sitewhere-mongodb-secondary-0
Annotations:        <none>
Status:             Running
IP:                 10.244.2.103
Controlled By:      StatefulSet/sitewhere-mongodb-secondary
Containers:
  mongodb-secondary:
    Container ID:   docker://8101337871e31e41bb470f5458d5756486a6925b047ee18ddd902e2104ebbd86
    Image:          docker.io/bitnami/mongodb:4.0.3
    Image ID:       docker-pullable://bitnami/mongodb@sha256:f06a3c8adf3cf4ea2a4205763262b4584a13abca6bd230fb3b0d2a1de4a015fe
    Port:           27017/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    14
      Started:      Thu, 07 Mar 2019 01:59:11 +0000
      Finished:     Thu, 07 Mar 2019 01:59:17 +0000
    Ready:          False
    Restart Count:  129
    Liveness:       exec [mongo --eval db.adminCommand('ping')] delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:      exec [mongo --eval db.adminCommand('ping')] delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      MONGODB_SYSTEM_LOG_VERBOSITY:  0
      MONGODB_DISABLE_SYSTEM_LOG:    no
      MONGODB_POD_NAME:              sitewhere-mongodb-secondary-0 (v1:metadata.name)
      MONGODB_REPLICA_SET_MODE:      secondary
      MONGODB_PRIMARY_HOST:          sitewhere-mongodb
      MONGODB_REPLICA_SET_NAME:      rs0
      MONGODB_ADVERTISED_HOSTNAME:   $(MONGODB_POD_NAME).sitewhere-mongodb-headless.default.svc.cluster.local
      MONGODB_ENABLE_IPV6:           yes
    Mounts:
      /bitnami/mongodb from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2tmxh (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir-sitewhere-mongodb-secondary-0
    ReadOnly:   false
  default-token-2tmxh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2tmxh
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                    From                Message
  ----     ------   ----                   ----                -------
  Normal   Pulled   5m16s (x130 over 12h)  kubelet, vm-ubuntu  Successfully pulled image "docker.io/bitnami/mongodb:4.0.3"
  Warning  BackOff  18s (x2998 over 12h)   kubelet, vm-ubuntu  Back-off restarting failed container

### **liusong@ubuntu18-4th:~$ k describe pods/sitewhere-consul-0**
Name:               sitewhere-consul-0
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             chart=consul-3.5.0
                    component=sitewhere-consul
                    controller-revision-hash=sitewhere-consul-c5b745fff
                    heritage=Tiller
                    release=sitewhere
                    statefulset.kubernetes.io/pod-name=sitewhere-consul-0
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      StatefulSet/sitewhere-consul
Containers:
  sitewhere-consul:
    Image:       consul:1.0.0
    Ports:       8500/TCP, 8400/TCP, 8301/TCP, 8301/UDP, 8302/TCP, 8302/UDP, 8300/TCP, 8600/TCP, 8600/UDP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/UDP, 0/TCP, 0/UDP, 0/TCP, 0/TCP, 0/UDP
    Command:
      /bin/sh
      -ec
      IP=$(hostname -i)
      if [ -e /etc/consul/secrets/gossip-key ]; then
        echo "{\"encrypt\": \"$(base64 /etc/consul/secrets/gossip-key)\"}" > /etc/consul/encrypt.json
        GOSSIP_KEY="-config-file /etc/consul/encrypt.json"
      fi
      
      for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
          while true; do
              echo "Waiting for ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME} to come up"
              ping -W 1 -c 1 ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME}.${STATEFULSET_NAMESPACE}.svc > /dev/null && break
              sleep 1s
          done
      done
      
      PEERS=""
      for i in $(seq 0 $((${INITIAL_CLUSTER_SIZE} - 1))); do
        NEXT_PEER="$(ping -c 1 ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME}.${STATEFULSET_NAMESPACE}.svc | awk -F'[()]' '/PING/{print $2}')"
        if [ "${NEXT_PEER}" != "${POD_IP}" ]; then
          PEERS="${PEERS}${PEERS:+ } -retry-join ${STATEFULSET_NAME}-${i}.${STATEFULSET_NAME}.${STATEFULSET_NAMESPACE}.svc"
        fi
      done
      
      exec /bin/consul agent \
        -ui \
        -domain=consul \
        -data-dir=/var/lib/consul \
        -server \
        -bootstrap-expect=${INITIAL_CLUSTER_SIZE} \
        -disable-keyring-file \
        -bind=0.0.0.0 \
        -advertise=${IP} \
        ${PEERS} \
        ${GOSSIP_KEY} \
        -client=0.0.0.0 \
        -dns-port=${DNSPORT} \
        -http-port=8500
      
    Liveness:  exec [consul members -http-addr=http://127.0.0.1:8500] delay=300s timeout=5s period=10s #success=1 #failure=3
    Environment:
      INITIAL_CLUSTER_SIZE:   3
      STATEFULSET_NAME:       sitewhere-consul
      POD_IP:                  (v1:status.podIP)
      STATEFULSET_NAMESPACE:  default (v1:metadata.namespace)
      DNSPORT:                8600
    Mounts:
      /etc/consul/secrets from gossip-key (ro)
      /var/lib/consul from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2tmxh (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir-sitewhere-consul-0
    ReadOnly:   false
  gossip-key:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  sitewhere-consul-gossip-key
    Optional:    false
  default-token-2tmxh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2tmxh
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**Comment by derekadams** [comment]
Can you provide more information about the runtime environment? For instance, which cloud provider if running in the cloud or your local system configuration if not. Also the output of:

`kubectl version`
`helm version`
`kubectl get pvc`

From the failures you mention, it sounds like the persistent volumes are not able to be created. If the `STATUS` values for your PVCs are not `Bound` it's a good indicator.

**Comment by alanliu95** [comment]
Thanks for your answer first. 
My k8s cluster is based on our lab server. one is physical machine running ubuntu18. Another is vmware machine running ubuntu16.
output "kubectl version" 
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

output "helm version"
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

output "kubectl get pvc"
NAME                                    STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
data-sitewhere-zookeeper-0              Bound     pvc-0c900fef-1cb5-11e9-a7d0-509a4c603ddf   5Gi        RWO            rook-ceph-block   45d
data-sitewhere-zookeeper-1              Pending                                                                        standard          22h
datadir-sitewhere-consul-0              Pending                                                                                          45d
datadir-sitewhere-kafka-0               Bound     pvc-0c984f77-1cb5-11e9-a7d0-509a4c603ddf   1Gi        RWO            rook-ceph-block   45d
datadir-sitewhere-mongodb-primary-0     Bound     pvc-0ca997e5-1cb5-11e9-a7d0-509a4c603ddf   8Gi        RWO            rook-ceph-block   45d
datadir-sitewhere-mongodb-secondary-0   Bound     pvc-0ccac953-1cb5-11e9-a7d0-509a4c603ddf   8Gi        RWO            rook-ceph-block   45d

**Comment by derekadams** [comment]
The versions of the tools look fine, so it's almost surely the PVCs causing the issues. Was there a previous installation of SiteWhere on the cluster? It looks like some of the PVCs were created around 45 days ago. I would suggest shutting down the Helm installation with:

`helm del sitewhere --purge`

then removing the existing data by issuing:

`kubectl delete pvc -l release=sitewhere`

After that, perform a new Helm install. It looks like some of the existing PVCs bound successfully, so I don't think there is a problem with the underlying storage settings.

**Comment by alanliu95** [comment]
actually, it is pvcs causing the issues. My cluster doesn't the "standard" storageclass. After I added default storageclass and "standard" storageclass. Those pods start to work.
Thanks much for your help.
