### ISSUE TITLE
Is it possible to make sitewhere 2.0 avoid k8s "LoadBalancer" service type?

### ISSUE THREAD

**Issue by alanliu95** [sitewhere/sitewhere#699]
I just have a local custom k8s cluster which is built by "kubeadm". So my k8s cluster doesn't support "LoadBalancer" service type. I want to if it is possibe to use "NodePort" to replace "LoadBalancer". if possible, is there any document to instruct how to modify the reponding chart configuration file.
Thanks in advance.

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @alanliu95,

You can override the default configuration by executing a helm install like:

```console
helm install --name sitewhere \
--set infra.mosquitto.service.type=NodePort \
--set services.web_rest.service.http.type=NodePort \
sitewhere/sitewhere
```
This will overrides Web/Rest [http](https://github.com/sitewhere/sitewhere-k8s/blob/494303c4a9db84e32fe1f2cd2e13567057c1cf84/charts/sitewhere/values.yaml#L177) and [Mosquitto](https://github.com/sitewhere/sitewhere-k8s/blob/494303c4a9db84e32fe1f2cd2e13567057c1cf84/charts/sitewhere/values.yaml#L34).
Hope this help.

**Comment by alanliu95** [comment]
It works. Thanks much.
