### ISSUE TITLE
How to access swagger ui , what's the url ? I use sitewhere 2.0

### ISSUE THREAD

**Issue by billy1999** [sitewhere/sitewhere#709]

**Comment by derekadams** [comment]
The URL pattern is `http://localhost:8080/sitewhere/swagger/` if you are running locally. Otherwise replace the hostname and port depending on where SiteWhere is running. There is a separate Swagger instance for the authentication UI (for getting a JWT) at `http://localhost:8080/sitewhere/auth/`.

**Comment by billy1999** [comment]
thank you
