### ISSUE TITLE
How to send commands and receive device message by mqtt?

### ISSUE THREAD

**Issue by billy1999** [sitewhere/sitewhere#710]
For example, the android app, how to control devices in real time and receive device information

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @billy1999, please take a look at the [User Guide](https://sitewhere.io/docs/2.0.0/guide/devices/android.html).
Also you can find an android [example](https://github.com/sitewhere/sitewhere-android-sdk/tree/master/example) on GitHub.
