### ISSUE TITLE
Use Kafka rather than gRPC for transmitting inbound events for storage

### ISSUE THREAD

**Issue by derekadams** [sitewhere/sitewhere#733]
The 2.0 approach of pushing events from inbound event processing to event management for storage via gRPC could be sped up significantly by using Kafka instead. This approach would also making the entire event processing pipeline Kafka-driven for a consistent event flow. Add a producer for events that have been enriched in inbound processing and a consumer in event management which takes the batches of events and stores them.

**Comment by ATM006** [comment]
By the way, I use Kafka command-line tool to track inbound events, and there is no event management. Moreover, we did not see any messages on the topic of event persistence.

附议，我使用kafka命令行工具追踪入站事件，到了事件管理就没有了。而且，没有看到事件持久的主题有消息。
