### ISSUE TITLE
How to send mqtt json message information in version 2.1.0？

### ISSUE THREAD

**Issue by saisy** [sitewhere/sitewhere#778]
send the data like this:
{
  "type": "DeviceMeasurement",
  "originator": "device",
  "deviceToken": "33557-MT90-9582885",
  "request": {
    "name": "temp11",
    "value": "34.7",
    "updateState": true,
    "eventType":"Measurement",
    "eventDate": "2018-11-21T22:10:13.418-0300",
    "metadata": {
      "name1": "val1",
      "name2": "val2"
    }
  }
}
but it won't work.
Report error message:Unable to convert event create request to API. EVENT_NOT_SET  
or 
You must provide credentials to perform this action.

**Comment by hhj1995** [comment]
{
  "type": "DeviceMeasurement",
  "originator": "device",
  "deviceToken": "test6-device-c",
  "request": {
     "name": "temp",
     "value": "170",
    "updateState": true,
    "eventDate": "2020-06-12T11:40:04.390Z",
    "metadata": {
      "name1": "val1",
      "name2": "val2"
    }
  }
}
这种是生效的，不过您知道怎么发送多个测量数据吗？这种只能发送一个

**Comment by hhj1995** [comment]
How to send multiple measurements？

**Comment by hhj1995** [comment]
How to send multiple measurements？
