### ISSUE TITLE
How to custom fields forwards to Azure EventHub

### ISSUE THREAD

**Issue by Abel-Liu** [sitewhere/sitewhere#79]
Hi, I am forwarding data to Azure EventHub, and I got this:

{
        "id": "584526d74f7bfbeb50f1a289",
        "eventType": "Measurements",
        "siteToken": "525ba813-a820-4ebb-b0a1-3886fc405cf6",
        "deviceAssignmentToken": "ce8730ff-0bd1-4f17-ac14-4191e453f472",
        "assignmentType": "Unassociated",
        "eventDate": "2016-12-05T08:35:35.8870000",
        "receivedDate": "2016-12-05T08:35:35.8870000",
        "measurements": {
            "yungoaltest": 636165525926941000
        },
        "measurementsSummary": "yungoaltest: 6.3616552592694106E17",
        "metadata": {},
        "EventProcessedUtcTime": "2016-12-05T08:40:57.7297691Z",
        "PartitionId": 3,
        "EventEnqueuedUtcTime": "2016-12-05T08:36:35.5420000Z"
    }

There is no hardwareid include. How can I add hardwareid when sending data?
Thank you very much.

**Comment by derekadams** [comment]
We do not currently support customizing the fields that are sent to EventHub. We added an issue for the 1.10.0 release to investigate allowing the fields to be customized.

https://sitewhere.atlassian.net/browse/SITEWHERE-365

In the meantime, you can make a REST call to get the assignment details based on `deviceAssignmentToken`. The response includes the `hardwareId` and other assignment information.

**Comment by Abel-Liu** [comment]
Thank you for response & thanks for your work.
