### ISSUE TITLE
After 2.0, which version is the most stable

### ISSUE THREAD

**Issue by CCThinkBank** [sitewhere/sitewhere#791]
After 2.0, which version is the most stable？

**Comment by derekadams** [comment]
SiteWhere 2.1 (https://github.com/sitewhere/sitewhere/releases/tag/sitewhere-2.1.0) is the current stable release. It has some significant architectural improvements over 2.1. We are also working on the new 3.0 release which will be available early in Q1 2020 (https://github.com/sitewhere/sitewhere/issues/789)
