### ISSUE TITLE
About com.sitewhere.grpc.model.DeviceEventModel implementation

### ISSUE THREAD

**Issue by CCThinkBank** [sitewhere/sitewhere#794]
where can I find the com.sitewhere.grpc.model.DeviceEventModel implementation *.proto files？
Is it can not change and don't open source?

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @CCThinkBank,

Here is the definition of [com.sitewhere.grpc.model.DeviceEventModel](https://github.com/sitewhere/sitewhere-grpc-api/blob/master/sitewhere-grpc-event-management/src/main/proto/device-event-model.proto), this file is compile using Google Protocol Buffer into java clases. 

[EventManagementImpl](https://github.com/sitewhere/sitewhere/blob/master/service-event-management/src/main/java/com/sitewhere/microservice/grpc/EventManagementImpl.java) is the class that implements the gRPC service in SiteWhere.
Hope this helps.

**Comment by derekadams** [comment]
Also, you can ask these types of questions on our Discord server rather than using GitHub issues. Click the following link to access the server: https://discord.gg/3rbZA4
