### ISSUE TITLE
How to understand "Streaming Media" event ?  

### ISSUE THREAD

**Issue by CCThinkBank** [sitewhere/sitewhere#795]
ALL the messages  comes from mqtt  and then decodes to a event by Inbound-Service. what is the Streaming-Media-Event content and  the application scenario (kindly give a example please )?

**Comment by derekadams** [comment]
The streaming media microservice is not completely implemented yet. The goal is to support uploading audio and video media and storing the data in existing media servers. The current implementation is just a simple prototype of storing a stream into a MongoDB persistence store.
