### ISSUE TITLE
Some questions about version 1.7, whether version 1.x is no longer available?

### ISSUE THREAD

**Issue by yuyewuye** [sitewhere/sitewhere#799]
I am currently using sitewhere1.7,but when i want to create a new device,i don't konw how to do it .At postman software,I "Get http://localhost:8080/sitewhere/api/sites" .it response ""timestamp": 1581532133397,
    "status": 401,
    "error": "Unauthorized",
    "message": "Full authentication is required to access this resource",
    "path": "/sitewhere/api/sites"
Please reply me ,thank you very much!!!!!!

**Comment by derekadams** [comment]
Hi @yuyewuye You'll need to pass HTTP basic authentication information to authenticate the user making the request. This can be accomplished by passing the HTTP `Authorization` header (which can be enabled in Postman).

Regarding SiteWhere 1.x, it has reached end-of-life and is no longer under active development. You can still download it or build it from GitHub, but no new features or bug fixes are being addressed.

We will be releasing the first beta of SiteWhere 3.0 in the next few weeks and advise using SiteWhere 2.x or the new beta rather than 1.x.

**Comment by yuyewuye** [comment]
Thank you for your prompt reply.


Sitewhere fascinates me,because we're building a very large Internet of things platform，so I want to test the 1.x version first。



You see：




and then i “Try it out”Please reply me ,thank you.



Finaly，I want to konw ,Do you have any partners in China?Maybe we will have a great cooperation.






殷虎





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Derek Adams"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月13日(星期四) 凌晨2:51
收件人:&nbsp;"sitewhere/sitewhere"<sitewhere@noreply.github.com&gt;;
抄送:&nbsp;"殷虎"<85304810@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [sitewhere/sitewhere] Some questions about version 1.7, whether version 1.x is no longer available? (#799)




Hi @yuyewuye You'll need to pass HTTP basic authentication information to authenticate the user making the request. This can be accomplished by passing the HTTP Authorization header (which can be enabled in Postman).
 
Regarding SiteWhere 1.x, it has reached end-of-life and is no longer under active development. You can still download it or build it from GitHub, but no new features or bug fixes are being addressed.
 
We will be releasing the first beta of SiteWhere 3.0 in the next few weeks and advise using SiteWhere 2.x or the new beta rather than 1.x.

**Comment by yuyewuye** [comment]
if i want to creat a new device in sitewhere 1.X,could you give me a Demo ?




殷虎





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Derek Adams"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月13日(星期四) 凌晨2:51
收件人:&nbsp;"sitewhere/sitewhere"<sitewhere@noreply.github.com&gt;;
抄送:&nbsp;"殷虎"<85304810@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [sitewhere/sitewhere] Some questions about version 1.7, whether version 1.x is no longer available? (#799)




Hi @yuyewuye You'll need to pass HTTP basic authentication information to authenticate the user making the request. This can be accomplished by passing the HTTP Authorization header (which can be enabled in Postman).
 
Regarding SiteWhere 1.x, it has reached end-of-life and is no longer under active development. You can still download it or build it from GitHub, but no new features or bug fixes are being addressed.
 
We will be releasing the first beta of SiteWhere 3.0 in the next few weeks and advise using SiteWhere 2.x or the new beta rather than 1.x.

**Comment by derekadams** [comment]
Are you able to join our Discord server at this URL? https://discord.gg/sq7sH7B
If so, it will be easier to interact on there. Thanks!

**Comment by yuyewuye** [comment]
Hi dear：
&nbsp; &nbsp; I have&nbsp; deployed sitewhere of 2.1 version。But i couldn't find the complete teaching document and sample.Can you provide an architecture document and operation manual?


Thank you!









Yinhu





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Derek Adams"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月13日(星期四) 凌晨4:25
收件人:&nbsp;"sitewhere/sitewhere"<sitewhere@noreply.github.com&gt;;
抄送:&nbsp;"殷虎"<85304810@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [sitewhere/sitewhere] Some questions about version 1.7, whether version 1.x is no longer available? (#799)




Are you able to join our Discord server at this URL? https://discord.gg/sq7sH7B
 If so, it will be easier to interact on there. Thanks!
