### ISSUE TITLE
A simple question about authorization

### ISSUE THREAD

**Issue by huangweiboy2** [sitewhere/sitewhere#801]
Can you tell me which restapi can get jwt token, or tell me how to access it directly, I am newbie

![image](https://user-images.githubusercontent.com/56343299/74821762-0f1faa80-533f-11ea-8590-581bf9414b15.png)

**Comment by huangweiboy2** [comment]
I saw this api key written here, so I'm confused, maybe I didn't find it

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @huangweiboy2,

There are two API relative URL in SiteWhere

1.  **SiteWhere Authentication APIs**: `http(s)://{host}:{port}/sitewhere/authapi/`: used for authentication in SiteWhere
2. **SiteWhere REST APIs**: `http(s)://{host}:{port}/sitewhere/api/`: used for managing SiteWhere objects and instances.

For obtaining a `JWT` use `http(s)://{host}:{port}/sitewhere/authapi/jwt` providing Basic access authentication. If the response is successful, the header `X-Sitewhere-JWT` will have the `JWT` you need for calling the REST API.

Hope this help

**Comment by huangweiboy2** [comment]
@jorgevillaverde-sitewhere Thank you, although I do n’t know if you are male or female
