### ISSUE TITLE
Error when creating new asset for persons or locations

### ISSUE THREAD

**Issue by uxout** [sitewhere/sitewhere#81]
Just started from fresh install sitewhere 1.8.0 CE with no sample data.
I wanted to create a new asset person (or location) from Admin Web UI and got this error on a popup window : "Unable to create asset."
I've found that this is due to a bug where the URL REST API used is wrong.
You should look :
[https://github.com/sitewhere/sitewhere/blob/364e328d764c641dbc3fe4ef7b9ca2734166cc03/sitewhere-web/src/main/webapp/WEB-INF/jsp/assets/locationAssetCreateDialog.inc](url) line 217.
**URL miss "/locations" in the end.**

Same thing for persons asset creation :
[https://github.com/sitewhere/sitewhere/blob/364e328d764c641dbc3fe4ef7b9ca2734166cc03/sitewhere-web/src/main/webapp/WEB-INF/jsp/assets/personAssetCreateDialog.inc](url) line 193.

Hope you can fix this for next version.
Thanks for you work :)

**Comment by derekadams** [comment]
Thanks for reporting the problem. It's fixed in the 1.9.0 release which will be available today.
