### ISSUE TITLE
how to cluster deploy?

### ISSUE THREAD

**Issue by hanyou** [sitewhere/sitewhere#82]
how to cluster deploy sitewhere?

**Comment by derekadams** [comment]
SiteWhere CE is not intended to be clustered. It is possible to run multiple instances to handle larger loads, but we do not provide support for clustering in CE. We do offer SiteWhere Enterprise Edition which is a complete clustered solution deployed on Docker Swarm. It includes a SiteWhere Cluster Manager with elastic scaling, real-time monitoring, data migration, and many other enterprise features. SiteWhere EE is currently in early beta with our core partner network.

**Comment by hanyou** [comment]
look forward to it, when release?

**Comment by derekadams** [comment]
SiteWhere EE will enter beta on January 15, 2017 for our existing commercial customers. Soon afterward, we will offer SiteWhere EE/CM as a subscription-based product for general commercial use.
