### ISSUE TITLE
about deploy 2 instance

### ISSUE THREAD

**Issue by hanyou** [sitewhere/sitewhere#83]
i have deploy 2 instance sitewhere, how to share tenant's config file?

**Comment by derekadams** [comment]
We do not support centralized configuration in SiteWhere CE. SiteWhere EE and SiteWhere Cluster Manager provide a central repository for configuration files and other resources, allowing for horizontally scalable clusters of SiteWhere nodes. A standalone SiteWhere EE instance can upload its configurations to the CM repository, which is used to bootstrap SiteWhere clusters. Note that SiteWhere EE/CM are the commercial products built on top of SiteWhere CE.

**Comment by slgxmh** [comment]
I have some problems.I running sitewhere by docker
Where is conf/sitewhere-server.xml exactly?
3q.

**Comment by derekadams** [comment]
If you start a shell inside the running SiteWhere container, the SiteWhere configuration is available in the `/opt/sitewhere/conf` folder
