### ISSUE TITLE
Delate Rule management and refactor some server in Version 3.0

### ISSUE THREAD

**Issue by yuyewuye** [sitewhere/sitewhere#837]
I've seen the rule management service removed from version 3.0,is it ture? ?Is there a significant change compared with 2.1.1  at Event management server and decive state server ? June 13th have passed ,when you can be release new Version?

**Comment by derekadams** [comment]
We ran into some event pipeline issues that prevent using event sources in the 3.0 code. We are working on those issues now. The rule management service was a placeholder in 2.1.1 and will eventually be replaced by separate microservices for multiple rule management and/or CEP providers. Regarding the event management and device state microservices, they are essentially the same as the ones in 2.1.1. As soon as the core system is functioning, we will release the beta (probably in the next week or so).

**Comment by yuyewuye** [comment]
Thank you .I hope the new version can fix #824 、#831 、 #834 and the another bugs in 2.1.1 .Because they are so important that 2.1.1 is not available.I'm looking forward to the new release next week.

**Comment by derekadams** [comment]
Yes, we plan to address all of those 👍

**Comment by yuyewuye** [comment]
✊



---Original---
