### ISSUE TITLE
Hello, is 2.2.0 a complete version of 2.1.1?

### ISSUE THREAD

**Issue by liwh1111** [sitewhere/sitewhere#887]
Hello, is 2.2.0 a complete version of 2.1.1? But I have been loading configuration since 2.2.0 was launched, so I cannot use it. What's the matter?

![image](https://user-images.githubusercontent.com/63097736/93289811-e054ae80-f811-11ea-947e-1b3f1ef96b56.png)

**Comment by derekadams** [comment]
We didn't release `2.2.0` since the work we did there was not completed. Instead, we moved to the new architectural approach used in `3.0.0`.
