### ISSUE TITLE
upload multiple event by MQTT's jsonbatch topic

### ISSUE THREAD

**Issue by webb-lu** [sitewhere/sitewhere#9]
hi Adam,
I upload the measurements, alerts and locations via MQTT's jsonbatch topic, and it works fine,
```
{  
   "hardwareId":"hwid",
   "measurements":[  
      {  
         "eventDate":"2015-06-05T09:07:25.725Z",
         "measurements":{  
            "measureTitle1":123,
            "measureTitle2":0
         },
         "metadata":{  
            "metaTitle1":"test metadata"
         }
      }
   ]
}
```
but I need to send every single event separately,

Could I send many measurements just by one MQTT package?
Just like the POST method `/devices/{hardwareId}/batch`
I have tested this format below, but it's failed.
```
{  
   "hardwareId":"hwid",
   "measurements":[  
      {  
         "eventDate":"2015-06-05T09:07:25.725Z",
         "measurements":{  
            "measureTitle1":123,
            "measureTitle2":0
         },
         "metadata":{  
            "metaTitle1":"test metadata"
         }
      },
      {  
         "eventDate":"2015-06-05T09:07:25.725Z",
         "measurements":{  
            "measureTitle1":"webbbbbbbbbbb",
            "measureTitle2":"bbaaaaaaaaaa"
         },
         "metadata":{  
            "metaTitle1":"mmmmmetaaaaaa"
         }
      }
   ]
}
```

Thanks~
Webb

**Comment by derekadams** [comment]
Hello Webb,

You can definitely send multiple events in a single batch request. The problem you are running into is that string values are being passed for measurements in the second request. Measurements are always numeric. If you want to store a non-numeric value, you can either add the value as a metadata field on the measurements event, or you can add a separate alert event into the batch and use the non-numeric value as the 'message' field. The preferred approach is to use a separate alert in this case.

Regards,
Derek

**Comment by webb-lu** [comment]
hi Adams,
Sorry, I totally forget that. Thanks your help !!

Best Wishes,
Webb
