### ISSUE TITLE
install  error ,How to solve it

### ISSUE THREAD

**Issue by brewswang** [sitewhere/sitewhere#903]
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"]

**Comment by derekadams** [comment]
The SiteWhere Helm charts require that Istio has been installed beforehand. Please verify that Istio was successfully installed so that the dependencies are available.
