### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by nginxsantos** [sitewhere/sitewhere#91]
Can this be used in a commercial deployment? What is the clause?

The CPAL looks to be a variation of GPL, including the copyleft requirement of distributing the modifications openly.   It looks like a restrictive as GPL and not open like BSD.

Thanks.....

**Comment by derekadams** [comment]
SiteWhere CE is available under the CPAL 1.0 license, which allows for use in commercial deployments. CPAL requires that any additions you make to the core SiteWhere code (not applications that run on top of SiteWhere), be submitted back to the open source project. It is also a "badgeware" license, which means any product that uses SiteWhere must acknowledge that it is powered by SiteWhere. This does not prohibit commercial use of SiteWhere or result in "viral" effects as seen with GPL.

We also offer SiteWhere Enterprise Edition which is licensed commercially and supports white labeling of products based on SiteWhere without the need for attribution or returning code to the open source version. SiteWhere EE offers elastic scalability, real-time health monitoring, and many other industrial-strength features, and is being released to beta customers in Q2 2017.
