### ISSUE TITLE
V3.0

### ISSUE THREAD

**Issue by yuyewuye** [sitewhere/sitewhere#913]
Hi,buddy!
First and foremost, let me wish you, your families, and the populations you represent all the best for a healthy New Year.
Do you have any problems with the new version?My team use SiteWhere 1.0 and experience is very good ,and tested in a production environment.In Sitewhere 2.0 ,we did a lot of research and reinvention,but there are still many problems.We have reintegrated siddhi and Jupyter.I'm a little confused why not choose Node-RED?
And in Sitewhere 2.0 ,there is no user permission management ,moreover ,the function of tenant management is not perfect.
I'd like to make sure ,when will 3.0 be released ,or go straight to PE? We are looking forward to the release of the new version, after all, there are many Iot platforms,such as Thingsboard、wso2、Zetta……
If there is a commercial version, can we have an agent?
Hope to reply!

**Comment by derekadams** [comment]
Hi @yuyewuye, thanks for your post. We wish you a happy, healthy New Year as well!

We are nearing completion of work on SiteWhere CE 3.0 as well as the new Enterprise Edition offering. The plan is to release both in January along with complete documentation. We apologize for the issues with SiteWhere 2.0. The intent was to move toward a microservices architecture with that release, but there were issues that required more re-architecture and hence the 3.0 development initiative. 

The 3.0 release should address the user management issues you were seeing. In 3.0, we have moved to [Keycloak](https://www.keycloak.org/) for user management and token generation, so it's a much more sophisticated model supporting better integration options. We have also cleaned up many aspects of tenant management and added tools that make it easy to create and configure SiteWhere instances. Hopefully, everything you liked from SiteWhere 1.x will again be available in 3.0 in addition to a lot of new features.

Please use this contact form to send your information (https://www.sitewhere.com/contact/) and we will set up a call to talk more about 3.0 and the new Enterprise Edition features.

Thanks!

**Comment by yuyewuye** [comment]
I hope you don't go back on your word this time and look forward to your new version rather than the buggy test version.It's play a joke.
please tell me why  Siddhi is no longer an option for 2.0?Node-RED is ok?
