### ISSUE TITLE
WSO2 Identity Manager

### ISSUE THREAD

**Issue by nginxsantos** [sitewhere/sitewhere#92]
I see that Siteshwhere takes the help of WSO2 Identity Manager for the Asset Management. But, is this only that or WSO2 Identity Manager is used for something more thing.

Is the multi tenancy, RBAC are the complete functionality of Sitewhere or WSO2.?

Also, is there any plug in/interface defined for the integration of WSO2 API Gateway.

Any info would be much appreciated.

**Comment by derekadams** [comment]
We currently only support using WSO2 Identity Manager for loading a list of person assets that can be assigned to devices. The multi-tenancy and user/security model are completely implemented in the SiteWhere code base, though we did abstract the user management behind APIs so it can be implemented elsewhere as well. We are looking at the possibility of supporting other systems for storage of user/role information, but have not started that effort yet. Also, we do not currently support the WSO2 API Gateway product.

**Comment by nginxsantos** [comment]
Thank you. Apologies for getting back late. I still have few questions...

1. Does Sitewhere support OAuth2 based authentication.  I guess it is done internally?
2. Does it have the flexibility of interacting with a thirdparty identity server? Can it talk to a thirdparty identity server for generating tokens and validating tokens etc....

Regards, Santos

**Comment by derekadams** [comment]
Sorry this issue fell through the cracks. We have been working on the new SiteWhere 2.0 architecture and have not had the bandwidth to work on user/identity management yet. Generally, the SiteWhere server is not meant to be customer-facing, but rather a middleware component, so we have focused less on user management features. We do plan to revisit this as part of the 2.x roadmap though.
