### ISSUE TITLE
Can SiteWhere CE 3.0.0 be installed now? I found that SWCTL-0.2.18 is still a beta version. Is SWCTL still updated with the latest version

### ISSUE THREAD

**Issue by liwh1111** [sitewhere/sitewhere#921]
Can SiteWhere CE 3.0.0 be installed now? I found that SWCTL-0.2.18 is still a beta version. Is SWCTL still updated with the latest version
![image](https://user-images.githubusercontent.com/63097736/104815324-ba3a2c00-584e-11eb-927f-c068b3d67be2.png)

**Comment by derekadams** [comment]
We have not pushed a version of `swctl` that defaults to the `3.0.0` images yet, but you can run the following command to run those images:

```
swctl create instance -t 3.0.0 sitewhere
```

We will be releasing a new version of `swctl` soon that will default to the new images.

**Comment by derekadams** [comment]
A new `swctl` version is available with the correct defaults: https://github.com/sitewhere/swctl/releases/tag/v0.3.0
