### ISSUE TITLE
Instance management microservice not retrying when Keycloak not available

### ISSUE THREAD

**Issue by derekadams** [sitewhere/sitewhere#923]
When instance management starts, it attempts to contact Keycloak to bootstrap the user management entities. If Keycloak is not available, the service fails and does not recover. Add logic that will retry if Keycloak is not available.

**Comment by yuyewuye** [comment]
hi，Can this problem be fixed recently？

**Comment by derekadams** [comment]
Yes, we'll be putting out a fix for the issue in the next few days.
