### ISSUE TITLE
Instance management unable to connect to Keycloak on startup

### ISSUE THREAD

**Issue by liwh1111** [sitewhere/sitewhere#930]
I have installed sitewhere-3.0.1, but there is still a problem with instance-management. Could you please tell me why

![image](https://user-images.githubusercontent.com/63097736/105625363-b49ea080-5e63-11eb-9f6b-596dc4d751b1.png)

**Comment by liwh1111** [comment]
Please tell me more documents of 3.0 will be issued

**Comment by derekadams** [comment]
Did you install using `swctl install`? It appears that the Keycloak service isn't running. What is the output from `kubectl -n sitewhere system get services`? Regarding the documentation, the documents at https://next.sitewhere.io/docs/ are the only ones we have so far, but we will be adding more over the next few days.

**Comment by liwh1111** [comment]
Hello, I installed 3.0.2, but the problem still persists
I installed it with swctl-0.4.4
![image](https://user-images.githubusercontent.com/63097736/106000260-96e26d00-60e9-11eb-9b81-c6731d0c36c3.png)

I set SiteCloak-KeyCloak-HTTP to nodePort, but I have to use HTTPS to log in.
![image](https://user-images.githubusercontent.com/63097736/106000462-cf824680-60e9-11eb-9aa1-ea5f976d7b52.png)
![image](https://user-images.githubusercontent.com/63097736/106001291-ba59e780-60ea-11eb-8a03-fbda53500789.png)
![image](https://user-images.githubusercontent.com/63097736/106001341-ca71c700-60ea-11eb-9246-eff73a1f23da.png)
![image](https://user-images.githubusercontent.com/63097736/106001510-02790a00-60eb-11eb-8876-d72d81acc3c1.png)
![image](https://user-images.githubusercontent.com/63097736/106001460-f2612a80-60ea-11eb-82d3-98d6b6ac250b.png)


Is it possible to change 'http://sitewhere-keycloak-http.sitewhere-system:80/auth' to 'https://sitewhere-keycloak-http.sitewhere-system:8443/auth' ?

Or how do I position the problem

**Comment by derekadams** [comment]
Can you provide the details for your environment including the output of `kubectl version` and verify that you are starting with a clean installation (after `swctl uninstall --purge`). The parts that stand out as non-standard from the above output are the `NodePort` setting for `sitewhere-keycloak-http` and the fact that external IPs are still in a `Pending` state (usually indicating that a load balancer is not installed on the k8s instance). This information should help us to understand the issue better.

**Comment by liwh1111** [comment]
I ran 'after SWCTL uninstall --purge'

These are some versions of my tools, may I ask what other information you need

![image](https://user-images.githubusercontent.com/63097736/106005317-13c41580-60ef-11eb-9e2a-5aab2777087d.png)

**Comment by derekadams** [comment]
The tool versions above should work well. Are you running locally in an environment such as Minikube or via a cloud provider? Also, are you making any customizations to the networking setup or using the defaults? We have successfully tested the current swctl/images with Minikube and Google Cloud, so I'm wondering if there is an environment issue.

**Comment by jorgevillaverde-sitewhere** [comment]
It seems that the `LoadBalancer` `<pending>` is the issue. You can access it by it's `NodePort` but the services are expecting the port 80. 
A walk around (until you install a LoadBalancer) would be to manually edit the deployments of the microservices environment variable `sitewhere.config.keycloak.api.port` to the port of your NodePort (in this case `30703`)

**Comment by liwh1111** [comment]
@derekadams  I installed a K8S cluster locally and did not set up the network
![image](https://user-images.githubusercontent.com/63097736/106007947-ceedae00-60f1-11eb-895f-8b78a38d44f6.png)
![image](https://user-images.githubusercontent.com/63097736/106008047-e5940500-60f1-11eb-99ac-6f7299fffd50.png)

**Comment by derekadams** [comment]
Ok, it appears that the cluster is not set up with a load balancer. You can add one such as MetalLB (https://metallb.universe.tf/) which will allow ports to be exposed externally. Using the `NodePort` setting for `sitewhere-keycloak-http` will cause issues as @jorgevillaverde-sitewhere mentioned because the services expect to connect to a well-known port (80 in this case). You could manually set the port in each service by environment as mentioned above, but it's probably easier to use a load balancer if you want to interact with the cluster. As is, you will run into issues with MQTT and other externally-facing services with your existing configuration.

**Comment by liwh1111** [comment]
Hi, I didn't set the load balancer. I just set the nodePort to test if KeyCloak is available. I still don't know what is causing the following problem

![image](https://user-images.githubusercontent.com/63097736/106010359-4fada980-60f4-11eb-9156-82638e58946c.png)

**Comment by jorgevillaverde-sitewhere** [comment]
The problem is that the services are trying to access to `http://sitewhere-keycloak-http.sitewhere-system:80` and that resolves to a `LoadBalancer` port, not a `NodePort` port. So, Kubernetes can not send traffic to the correct services.

**Comment by liwh1111** [comment]
@jorgevillaverde-sitewhere Thank you. What should I do? I have to install a load balancer?

**Comment by jorgevillaverde-sitewhere** [comment]
yes, you need a load balancer. Just in case, can you post the result of 
```console
kubectl get svc -n sitewhere-system
```
and
```console
kubectl get pod -n sitewhere-system
```
Thanks

**Comment by liwh1111** [comment]
![image](https://user-images.githubusercontent.com/63097736/106018315-593b0f80-60fc-11eb-81b8-b446b80e6a45.png)

**Comment by jorgevillaverde-sitewhere** [comment]
That looks correct. Notice that `sitewhere-keycloak-http` is `ClusterIP` and not `NodePort` as in your previous image.
Are the microservices still failing to connect to Keycloak?

**Comment by liwh1111** [comment]
@jorgevillaverde-sitewhere Yes, I went from 3.0.0 to 3.0.2 and the problem persisted

**Comment by liwh1111** [comment]
All microservices in Namespace SiteWhere report this error
![image](https://user-images.githubusercontent.com/63097736/106020398-b041e400-60fe-11eb-885e-2526a87e0920.png)

**Comment by liwh1111** [comment]
Hello, I tried to access 'http://sitewhere-keycloak-http.sitewhere-system:80' from Instance-Management container, yes, there is a return message, can you guess that there may be a problem
![image](https://user-images.githubusercontent.com/63097736/106423464-70cb1d00-649b-11eb-9bd9-2d090dba59c9.png)

**Comment by jorgevillaverde-sitewhere** [comment]
So, from `instance-management` microservice you are able to access Keycloak but the services are still failing?

**Comment by liwh1111** [comment]
Hello, I have successfully installed it in another environment. Maybe there is something wrong with my current test environment. Thank you for your help
