### ISSUE TITLE
ERROR! SiteWhere WAR not found.

### ISSUE THREAD

**Issue by Pakato14** [sitewhere/sitewhere#95]
Hello! I am studying SiteWhere and installed the server, mongo DB, HiveMQ MQTT Broker and at the moment of starting the server the following message appears: "ERROR: SieteWhere WAR not found."

I am using linux ubuntu 16.04. I would like to know how to resolve this issue

Thank you

**Comment by derekadams** [comment]
Based on the error message, it looks like you are not running from a packaged SiteWhere distribution. If you download the zip or tar archive from the downloads page, unzip it, then run the startup script in the bin folder, it should work. If you are building SiteWhere from scratch, make sure you run the following Gradle command:

`gradle clean serverZip` or `gradle clean serverTar`

to create a complete installation.
