### ISSUE TITLE
Command delivery is not available，“Unhandled exception in producer while sending record.”

### ISSUE THREAD

**Issue by ATM006** [sitewhere/sitewhere#950]
“Unhandled exception in producer while sending record.”

![image](https://user-images.githubusercontent.com/24607498/110748448-b0dfa580-827a-11eb-85f3-f3deb91b1ddf.png)

In addition, how to send a command through mqtt？Do you provide demo

**Comment by derekadams** [comment]
We will reproduce the error locally and get it fixed in the `3.0.5` release. Regarding sending commands via MQTT, we do not have that functionality yet, but it will be easy enough to add. I will add a separate issue for it.

**Comment by derekadams** [comment]
https://github.com/sitewhere/sitewhere/issues/951
