### ISSUE TITLE
The test found that the database name（tenant_${tenant.id}） wildcard of influx did not take effect, resulting in the failure of data splitting between multi tenants

### ISSUE THREAD

**Issue by ATM006** [sitewhere/sitewhere#953]
The test found that the database name（tenant_${tenant.id}） wildcard of influx did not take effect, resulting in the failure of data splitting between multi tenants. I think it was a terrible accident.

![image](https://user-images.githubusercontent.com/24607498/111094775-f0f2a100-8576-11eb-98d1-d19cae1dffda.png)

**Comment by derekadams** [comment]
It appears that updates for generalizing the substitution logic in microservice configurations changed the value from `${tenant.id}` to `${tenant.token}`. We will add support for `${tenant.id}` to keep backward compatibility.
