### ISSUE TITLE
Why can't I contribute code 

### ISSUE THREAD

**Issue by ATM006** [sitewhere/sitewhere#954]
remote: Permission to sitewhere/sitewhere.git denied to ATM006.
fatal: unable to access 'https://github.com/sitewhere/sitewhere.git/': The requested URL returned error: 403

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @ATM006, you need to fork the repository, commit the changes in your own forked repository and then submit a Pull Request into SiteWhere repository. After that, we'll review the changes and, if applicable, merge then into the code base.

**Comment by ATM006** [comment]
Thank you
