### ISSUE TITLE
Command Invocation - None Required Fields Throw Error

### ISSUE THREAD

**Issue by garysmi2** [sitewhere/sitewhere#96]
When invoking a command with none required fields from the Web UI, an attempt is made to validate the type of the none required fields, as a result an error is shown in the Web UI. I think non required fields should only be validated if they actually contain some content.

In SiteWherePersistence checkData only null values are checked for, not empty strings so the validation process continues for none required fields even if they have no contents (or are whitespace)

For required fields that are of "string" type no check is done for empty string/whitespace contents so no error is thrown if no value has been provided for the required field which doesn't seem right.

I have a fix for this if required.

Cheers,

Gary.

**Comment by derekadams** [comment]
The field validation is definitely lacking at this point. Everywhere that we do checks for null fields should really be using commons StringUtils.isEmpty() to cover both the null and empty cases. I think the right way to go is to work on more formalized validation logic for all of the REST services so the handling is consistent. I added a Jira ticket to make sure we address the problem:

https://sitewhere.atlassian.net/browse/SITEWHERE-378

Thanks,
Derek

**Comment by garysmi2** [comment]
Recent merge from pull request should resolve this.
