### ISSUE TITLE
In the test, it is found that the default storage space of data 1Gi is too small

### ISSUE THREAD

**Issue by ATM006** [sitewhere/sitewhere#963]
In the test, it is found that the default storage space of '/var/lib/kafka/data' 1Gi is too small, can it be changed to the default automatic expansion, automatic expansion or configuration larger default parameters in swctl, chart... 
It is too easy to be full, and system stability cannot be guaranteed.

[kafka@sitewhere-kafka-kafka-0 kafka]$ df -h
Filesystem               Size  Used Avail Use% Mounted on
overlay                   50G   10G   41G  20% /
tmpfs                     64M     0   64M   0% /dev
tmpfs                    7.3G     0  7.3G   0% /sys/fs/cgroup
tmpfs                    7.3G   52K  7.3G   1% /tmp
/dev/mapper/centos-root   50G   10G   41G  20% /etc/hosts
shm                       64M     0   64M   0% /dev/shm
tmpfs                    7.3G   12K  7.3G   1% /opt/kafka/client-ca-certs
tmpfs                    7.3G   12K  7.3G   1% /opt/kafka/cluster-ca-certs
tmpfs                    7.3G     0  7.3G   0% /var/opt/kafka
tmpfs                    7.3G   48K  7.3G   1% /opt/kafka/broker-certs
/dev/rbd6                976M  6.1M  954M   1% /var/lib/kafka/data
tmpfs                    7.3G   12K  7.3G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                    7.3G     0  7.3G   0% /proc/acpi
tmpfs                    7.3G     0  7.3G   0% /proc/scsi
tmpfs                    7.3G     0  7.3G   0% /sys/firmware

**Comment by derekadams** [comment]
The default settings are not intended for high-traffic production deployment, but we do need to add flags that will allow the Kafka settings to be easily changed via the `swctl` command line rather than requiring the user to run from the Helm charts. For now though, you can run from the `sitewhere-infrastructure` Helm chart and change the default storage values for Kafka and/or other components such as the database.

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @ATM006,

You can use the flag `--kafka-pvc-size` to set the size of Kafka PVC when installing SiteWhere.
For example

```console
swctl install --kafka-pvc-size=10Gi
```

Please check [swctl install](https://next.sitewhere.io/open-source/documentation/deployment-guide/swctl/#install) documentation.

**Comment by ATM006** [comment]
Can influxdb storage space be configured like this？
swctl install --influxdb-pvc-size = 10Gi

**Comment by ATM006** [comment]
[root@iot-3-master-1 ~]# swctl install  --influxdb-pvc-size=20Gi 
Error: unknown flag: --influxdb-pvc-size

**Comment by jorgevillaverde-sitewhere** [comment]
We don't have that flag in `swctl install`. Please follow this [link](https://github.com/sitewhere/swctl/issues/40) for that feature request.
