### ISSUE TITLE
How to deploy a highly reliable production environment instead of swctl deploying all services in a cluster

### ISSUE THREAD

**Issue by ATM006** [sitewhere/sitewhere#968]
https://github.com/sitewhere/swctl

The current swctl deployment sitewhere instance is in a k8s cluster, I personally think it is very suitable for the test environment, but it is not very good to have hundreds of machines or more in the production and environment, because once the resource competition between kafka, database, and sw , The service is stable and cannot be guaranteed. Multi-cluster deployment is recommended, such as kafka cluster, zk cluster, database cluster, instance cluster, etc...

**Comment by derekadams** [comment]
We are looking at methods of scaling out the infrastructure and reducing contention between SiteWhere microservices and the infra components. For SiteWhere 3.x, we are still working on the core functionality and have not started focusing on performance and scalability yet. The default settings will work well for testing the system, but are not intended for production deployments. In particular, the default storage settings would not support large-scale event throughput. The 3.1 release will lower the memory requirements for the system significantly, after which we will focus on other aspects of performance.

**Comment by ATM006** [comment]
Can you give some suggestions, let me try
