### ISSUE TITLE
License, documentation, and developer resource concerns

### ISSUE THREAD

**Issue by kevin-canadian** [sitewhere/sitewhere#969]
Hi,

I am currently involved in an evaluation of various open-source IoT platforms. The company I work for has a multiple legacy IoT systems, and we're looking into various open-source platforms and components to use as part of a new foundation, to which we will migrate these various systems over time (as opposed to writing all the pieces ourselves).

I am very impressed with your overall architecture, and I would love to start using this as the basis for our next generation IoT platform. But I have three major concerns.

1. Currently, the LICENSE.txt indicates that this project is under the "Common Public Attribution License Version 1.0 (CPAL-1.0)", which is most likely a show-stopper for us, mainly because the nearly 200 lines of legalese is difficult to interpret without getting lawyers involved, and we just can't risk the legal exposure. In release 3.0.5 it appears that most of the file headers have been updated to use the "Apache License, Version 2.0", which would be perfect for us, but the LICENCE.txt file remains unchanged. Can you confirm what license governs the various parts of the source code, currently, and what your plans are regarding licensing moving forward?

2. The documentation available on the sitewhere.io website (and the sitewhere-documentation project on GitHub) is for 2.1.0, but the latest release is 3.0.5. I can understand that you have been very busy with the migration from 2.x to 3.x, so I get that you didn't quite manage to get the documentation included in the release (https://github.com/sitewhere/sitewhere/issues/878). I thought we might get started with the existing documentation, but from what I can see on the the wiki (https://github.com/sitewhere/sitewhere/wiki/SiteWhere-3.0) the changes are quite significant, which makes me reluctant to try to use the older documentation or just figure things out on the fly. How soon might we expect to have the documentation updated to 3.0? Obviously I don't expect you to be able to provide us with a hard date, but it would help us a lot if we could get a rough estimate (i.e. are we talking weeks, months, quarters, ...?).

3. The vast majority of the commits on the project seem to be made by Derek Adams (derekadams), with a few from Jorge Eduardo Villaverde (jorgevillaverde-sitewhere), and a very small number of other committers. It also seems that Derek is the one to respond to nearly all issues within the GitHub organisation. I don't want to sound indelicate, but how dependent is this project on you, Derek? ;) Obviously we're concerned about putting our eggs into a basket which is held together by one person.

Again, I think the solution you've built looks great, and I would love to start using it. To that end, I would appreciate any feedback you can provide related to the above concerns.

Best,
Kevin

**Comment by derekadams** [comment]
Hi @kevin-canadian Thanks for your interest in SiteWhere. Regarding your questions above:

1. As of SiteWhere 3.0, we have changed to the Apache 2.0 license. There were some files we missed in the original migration between licenses, but everything in the code should be updated at this point. As you mentioned, it looks like we did miss the `license.txt`, but the headers in the code are updated to Apache 2.0. We'll update the license file ASAP.
2. We are in the process of creating a new website and moving to a more standardized documentation format (same as is used in the Kubernetes documentation). We already have some of the documentation done and available at (https://next.sitewhere.io/open-source/documentation/), but we are still working on some of the other content before we make it available on the default web site.
3. I am the primary committer on the core project so far, though we have had a dedicated team for other aspects of the project beyond the open source. We have been heads-down with moving to the new 3.0 architecture for the last couple of years, so the project would have been a moving target for external contributors. We are moving toward having a larger, dedicated team, but are still working on those details.

**Comment by kevin-canadian** [comment]
Hi @derekadams,

Thanks for the lightning fast response. That is a good sign when it comes to the health of the project!

1. I am really glad to hear that the license has been updated, thanks for the clarification. This was actually my biggest concern.
2. The new documentation site looks good so far.  Any chance I can trick you into providing even a very rough ETA for when you think this might be complete? I promise not to hold you to it. ;) Also, is the source for this new documentation available somewhere under the SiteWhere GitHub organization, or is this internal-only for now?
3. Glad to hear you have a team backing you up, and that you're planning to grow. I understand how difficult that can be.

Again, thanks for the fast response, and keep up the good work!

**Comment by derekadams** [comment]
We have separate efforts for the website content and the documentation. A basic version of the new website homepage and some of the other content will be available in the next 2-3 weeks. For the documentation, we will be adding more iteratively over the next month or so. Most of our time right now is spent on the 3.1 release which moves the microservices to native images. It's a lot of work, so we haven't had much time to update the documentation yet. It's definitely on our short-term todo list though!

**Comment by kevin-canadian** [comment]
Perfect.  Thanks again for the quick responses.

**Comment by derekadams** [comment]
Sure, glad to help! If you have any questions before we have the documentation complete, feel free to contact me directly on our Discord server here: https://discord.gg/HXq8UR6f
